### ISSUE TITLE
Group automatically generated items

### ISSUE THREAD

**Issue by robkamp** [openhab/openhab-core#1000]
I would like to be able to add items to groups without using an item file for items that were generated automatic discovery/simple mode by PaperUI or HabMin for instance. The UI(s) do not seem to allow for this.

**Comment by cweitkamp** [comment]
In Paper UI you can create new groups when "Simple Mode" is disabled and also link items to existing groups.

Create group:
![group01](https://user-images.githubusercontent.com/5131747/63860444-6ef95200-c9a9-11e9-92fb-58786c5c0dd4.png)

Assign group:
![group02](https://user-images.githubusercontent.com/5131747/63860397-55f0a100-c9a9-11e9-90ac-bbd823f09534.png)

Otherwise I propose to move this issue to https://github.com/openhab/openhab-webui/issues. Thanks.
