### ISSUE TITLE
Rendering of command options

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#1016]
Command options is a new feature that is not yet supported neither in Basic UI nor in Classic UI. And I doubt it is in Android App too.

Before adding the support of this feature in Basic UI (and in few bindings), I would like to be sure to understand what is expected.

Command options can be different from state options.

I see 3 different cases:

1. the channel has only command options but no state (for example the clear queue channel of the Sonos binding)
2. the channel has command options and a state without state options
3. the channel has command options and a state with state options

I imagine the command options have to be considered when the user uses the switch or the selection sitemap element.

For the cases 1 and 2, we should render the command options as buttons for the switch element and as a selection for the selection element, the same as we do currently when having state options.

For the case 3, does it mean we have to consider command options + state options, meaning building one button for each command option + one button for each state option ? In this case, we have to consider only one item when one command option is the same as one item option ?

Last question is relative (again) to switch item. If I come back to my example, the clear queue channel is associated to a switch item. This channel should have only one command option: CLEAR. Is it acceptable for a switch element having command options to render it with buttons or a selection list ? I ask the question because it was recently rejected to render like that a switch item with state options. Or should we update the item type of this channel to String and only consider String and Number items for command options ?

@maniac103 @mueller-ma for Android App

**Comment by cweitkamp** [comment]
I looked into this topic today and see what you are meaning. I tried to model some channel typed from Kodi binding to support command options instead of state option. Here is the result from my testings in Paper UI and Basic UI:

Paper UI - command option are rendered as Push button(s) - state options are rendered as both  Selection and Button(s):
![grafik](https://user-images.githubusercontent.com/5131747/69012906-f63bdd80-097a-11ea-9b28-6618e0e5bf40.png)

Basic UI - Both Selection and Switch elements are empty:
![grafik](https://user-images.githubusercontent.com/5131747/69012916-0c499e00-097b-11ea-9deb-105d69b0d9c5.png)

`systemcommand` ("Systembefehl" in German) uses command options and `playfavorite` ("Favoriten" in German) uses state options.

Maybe it is a simple change in the [ItemUIRegistryImpl](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java#L342) - Exchange `item.getStateDescription();` by `item.getCommandDescription()` - maybe not.

But a little bit more theory in advance: State options are - in general - command options too. The [getCommandDescription()](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/items/GenericItem.java#L415) first tries to return a command description, if none is found the state description will be converted to a matching command description. IIRC for both applies that dynamic descritons are preferred.

What should be the Default element for command option? Selection too? Or just Push button(s) - because they have no state?

To your questions - I additionally like to suggest to take the label and pattern into account.:

1. I agree with your proposal. Patterns in labels should be removed completely.

2. I agree with your proposal. The state should be taken into account for the label similar to state options. Personally I don not think that a combination of command options and a state does not make sense.

3. This is the most interesting question. Did you read https://github.com/eclipse/smarthome/pull/5131 and try to find an answer or it? As above I personally do not think that a combination of both makes sense and state options should be preferred if needed. Command options should be only used for a matching use-case.

**Comment by cweitkamp** [comment]
@ghys Can you give me a short insight in how the new UI handles CommandOptions? Otherwise I will add `Switch` as Default element for rendering.

**Comment by ghys** [comment]
Simple: currently, it doesn't. But it's definitely something to consider and I suppose an [action sheet](https://framework7.io/vue/action-sheet.html#examples) would be an appropriate UI for those.

**Comment by cweitkamp** [comment]
Cool. Thanks. Looks nice. So it does not matter what we use here to solve this issue.
