### ISSUE TITLE
[REST] Item Metadata Selector Channel Missing After Config Refresh

### ISSUE THREAD

**Issue by jsetton** [openhab/openhab-core#1021]
When requesting for all items or a specific item with the channel metadata selector, the response will not include that property after refreshing the relevant item config files. Restarting the OH server resolves this issue.

Tests were done on the latest docker snapshot (2.5.0-SNAPSHOT Build 1676)

### Item
```
String temperature {alexa="TemperatureSensor.temperature", channel="nest:thermostat:account:xxxx:temperature"}
```

### Request
http://localhost:8080/rest/items/temperature?metadata=alexa,channel

#### Before Item Refresh

```
{
  "link": "http://localhost:8080/rest/items/temperature",
  "state": "79.0 °F",
  "stateDescription": {
    "pattern": "%.1f °F",
    "readOnly": true,
    "options": []
  },
  "metadata": {
    "channel": {
      "value": "nest:thermostat:account:xxxx:temperature"
    },
    "alexa": {
      "value": "TemperatureSensor.temperature"
    }
  },
  "editable": false,
  "type": "Number:Temperature",
  "name": "temperature",
  "tags": [],
  "groupNames": []
}

```

#### After Item Refresh
```
{
  "link": "http://localhost:8080/rest/items/temperature",
  "state": "79.0 °F",
  "stateDescription": {
    "pattern": "%.1f °F",
    "readOnly": true,
    "options": []
  },
  "metadata": {
    "alexa": {
      "value": "TemperatureSensor.temperature"
    }
  },
  "editable": false,
  "type": "Number:Temperature",
  "name": "temperature",
  "tags": [],
  "groupNames": []
}
```

**Comment by J-N-K** [comment]
IMO (and looking at the code) it is wrong that `channel` is reported at first call. `channel` is not metadata but channel-link configuration and that is why it is not added to the metadata on subsequent reads.

The root cause is that the `channel` part is parsed by a `BindingConfigReader` that is added as an optional service. The `GenericItemProvider` looks if a `BindingConfigReader` is available for the namespace and uses that instead of adding metadata. The reader is not available when the items file is parsed for the first time and metadata is not removed until the file is parsed again.

**Comment by jsetton** [comment]
> IMO (and looking at the code) it is wrong that `channel` is reported at first call. `channel` is not metadata but channel-link configuration and that is why it is not added to the metadata on subsequent reads.

Is this the reason why `channel` isn't reported for channel links created in the MainUI? I have considered using the `/links` endpoint in the past but currently there is no optimal way to get a list of channel links for a given item. Also, that endpoint requires admin privilege and wouldn't be available without using a token.
