### ISSUE TITLE
[Q] How to add a rfc2217://.. port in the UI (PaperUI, Habmin)

### ISSUE THREAD

**Issue by curlyel** [openhab/openhab-core#1029]
I'm trying to use rfc2217://...  remote serial ports with the Zigbee ~~and Zwave~~ binding.
When opening the serial port configuration for the dongles, I get a drop down list containing all local serial ports available in the underlaying Debian operation system and the JVM (physical as well as socat-provided virtual serial ports).

The list is pre-populated with the names of available serial ports but **does not allow manual add** of any port (e.g. undiscovered `rfc2217://<ip>:<port>`) 

But how to configure (add) a rfc2217 port then?

This list is not editable (same for PaperUI and Habmin):
![image](https://user-images.githubusercontent.com/11849305/64619422-5a25b100-d3e2-11e9-8eb6-8671f1491a33.png)

This is the platform:
```
Release   = Debian GNU/Linux 9 (stretch)
Kernel    = Linux 4.9.0-8-amd64
Platform  = VMware Virtual Platform
openHAB   = openHAB 2.5.0~M2-1 (Milestone Build)
Java      = Zulu 8.40.0.25-CA-linux64
```

Moved to here from `openhab-webui` https://github.com/openhab/openhab-webui/issues/117 according @cdjackson 's advice:
> .... since it’s populated by OH Core, and not the UI.

https://community.openhab.org/t/zwave-zigbee-rfc2217-remote-serial-port-howto/81633/16

**Comment by kaikreuzer** [comment]
I would say that this is a bug in the Z-Wave and Zigbee bindings.
If I look at the [parameter definition](https://github.com/openhab/org.openhab.binding.zigbee/blob/master/org.openhab.binding.zigbee.ember/src/main/resources/ESH-INF/thing/controller_ember.xml#L39-L44), it does not define `limitToOptions=false` and [its default value is true](https://www.openhab.org/docs/developer/bindings/config-xml.html#xml-structure-for-configuration-descriptions).
I would hope that changing it in the XMLs in the binding will solve the issue.
@cdjackson Could you give it a try?

**Comment by cdjackson** [comment]
Sure. I thought that all of this definition was added by the UI bundle somewhere.  I forget who added all this now.

**Comment by cdjackson** [comment]
So looking at this, we used to have this same configuration as it is now, then someone (I forget who) added the ```context="serial-port"``` and if I understand correctly, this has now broken things?

There is no ```limitToOptions``` and no default value. wouldn't it make sense that if these settings are required to be set, that it is done in a central place so that all bindings using this system work?

**Comment by cdjackson** [comment]
To emphasise my point that this should be resolved centrally, I did a search on the openhab2-addns folder. ```<context>serial-port</context>``` appears in 27 bindings - I didn't check all of them, but the first few that I checked are all configured the same as the ZigBee and ZWave binding - so that means that this "bug" in the bindings needs to be solved in over 30 places (given there are 4 or 5 places in the ZigBee binding, plus ZWave, plus potentially 27 other bindings).

I really think that this issue should be resolved in a single place - ie where-ever the config description is updated to add the . If that's not possible, then we'd need to fix it in all of the bindings using ```serial-context```.

**Comment by kaikreuzer** [comment]
It is a general behavior that when config options are provided, the UI shows them. There is no way to provide the `limitToOptions` value other than in the config descriptions themselves.

> If that's not possible, then we'd need to fix it in all of the bindings using serial-context.

In theory yes, but we might first want to check whether those bindings work in general with the rfc2217 ports - I am not so sure that this is the case for all of them.

**Comment by cdjackson** [comment]
> In theory yes, but we might first want to check whether those bindings work in general with the rfc2217 ports - I am not so sure that this is the case for all of them.

This issue, while opened against RFC2217 in my opinion is more general since I often see people on the forum complaining that their serial port is not listed in the list of ports as it wasn't picked up by whatever in the system provides this list. IMHO allowing users to type in their serial port themselves is a good idea. For example, I think if people use symbolic links to non-physical ports, it may not get picked up.

IMHO from a binding perspective, this is counter intuitive. The binding doesn't know anything about a list of options that is being added somewhere else in the system, so it doesn't add things like ```limitToOptions```. In some systems, this turns into a list of options, in other systems, it doesn't (a Mac doesn't provide a list - it just gives me a text box).

It seems to me that when we add a context to a description, that context should be able to change the description and if it can't, that seems to be a shortfall. Either that or we could remove the context?

**Comment by kaikreuzer** [comment]
>  IMHO allowing users to type in their serial port themselves is a good idea.

Ok, agreed.

> IMHO from a binding perspective, this is counter intuitive.

Yes, maybe. But the serial port is a special case anyhow as we don't have the situation for other parameters that the options are provided by the system and not by the binding.
I don't see an easy way to change it (and also don't think it is worth the effort to do major changes to the framework features just to cater for this special case), so my suggestion would be to stick with the suggested solution and simply add the `limitToOptions` info to the concerned config descriptions as it will nicely solve the issue.

**Comment by cdjackson** [comment]
Agreed - it's not the nicest, but I agree that it's not worth the hassle. I've now implemented this in ZigBee so it should now support RFC2217.

This can presumably now be closed.

**Comment by curlyel** [comment]
Many thanks!
