### ISSUE TITLE
same name for thing & item can produce problem

### ISSUE THREAD

**Issue by mwiedemann** [openhab/openhab-core#1047]
Hi,

I noticed a bug. I am sorry to say that I can not say how I produced this, but how I solved it.

I configured my KNX Shutter Actors to work with openhab (2.4 via Docker on RPi3). 
I came up with this setup:

home.things
```
Thing device knx_jalousieaktor_8_mitte "MDT Jalousieaktor 8-fach mitte" {
Type rollershutter :Rollo_EG_WEB_W_West [ upDown="3/2/14", stopMove="3/2/20" ]
}
```

home.items
```
Rollershutter Rollo_EG_WEB_W_West (EG_WEB,Rollos) {channel="knx:device:bridge:knx_jalousieaktor_8_mitte:Rollo _EG_WEB_W_West"}
```

home.sitemap
```
Default item=Rollo_EG_WEB_W_West label="Westen [%d %%]"
```

Moving my shutters up and down worked fine. But if I triggered the stop button (the one in the middle), again 3/2/14 was triggered. I tried several things without success.
Then I changed my config to this one. Notice the Name of things/items:

home.things
```
Thing device knx_jalousieaktor_8_mitte "MDT Jalousieaktor 8-fach mitte" {
Type rollershutter :Rollo_EG_WEB_W_West**2** [ upDown="3/2/14", stopMove="3/2/20" ]
}
```

home.items
```
Rollershutter Rollo_EG_WEB_W_West (EG_WEB,Rollos) {channel="knx:device:bridge:knx_jalousieaktor_8_mitte:Rollo _EG_WEB_W_West**2**"}
```

home.sitemap
```
Default item=Rollo_EG_WEB_W_West label="Westen [%d %%]"
```

Then it worked like a charm. Even after renaming the thing back to its first name (without "2") kept the configuration running fine. I have no idea how i produced this error. 

I had this problem with more that one thing/item. After this change on one thing, all things are working?!

Maybe my openhab.log can help you.

openhab.log: https://pastebin.com/E5RMgSUG
my physical address for openhab is 1.1.240

**Comment by t2000** [comment]
I just stumbled across this issue. @mwiedemann since you mention that changing the name back to the one which did NOT work at first, made it work in the end, I am wondering if you were affected by https://github.com/openhab/openhab-addons/pull/7603.

So, did you change the group addresses while editing the files? Because the mentioned PR targets exactly this! Changing the group addresses alone had no effect, but if I changed the item or channel names it started working.

So chances are that this bug is fixed. if you are working with snapshots, you could give latest one a try and start it with "item name == channel name" and see if it works out of the box.

Also i know that using the same name for a `thing` and and `item` definitly works, since I know a commercial product that is based on openHAB that creates a groupitem with the same name as the thing!
