### ISSUE TITLE
Persistence: restore at startup apparently broken

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#1053]
I installed this morning the snapshot 1703 and discovered that my persisted items were no more restored at startup.
I think it has been broken very recently. I will restore the snapshot 1698 later today to confirm that it was still working in this version.

Were there recent merged PRs that could impact persistence ?

**Comment by wborn** [comment]
Apparently some bundles aren't properly starting in the recent snapshot builds. Their state remains waiting (including persistence):

```
openhab> bundle:list|grep Waiting                                                                                       
133 │ Waiting │  80 │ 2.5.0.201909290301    │ openHAB Core :: Bundles :: Core
166 │ Waiting │  80 │ 2.5.0.201909290307    │ openHAB Core :: Bundles :: Model Persistence
181 │ Waiting │  80 │ 2.5.0.201909290306    │ openHAB Core :: Bundles :: Persistence
```

See also this [community topic](https://community.openhab.org/t/update-to-snapshot-1597-partially-failed-allplay-solved-amazondashbutton-wrapper-service-z-wave-solved/74930/70?u=wborn).

Maybe it's caused by one of your constructor injection PRs @cweitkamp?

**Comment by lolodomo** [comment]
I will check if some of my bundles are in waiting state later today.

**Comment by cweitkamp** [comment]
Yes, could be a valid reason. I will check on them later. Maybe there is an orphaned activate method like which I missed. Similar to what I fixed yesterday in #1051.

**Comment by wborn** [comment]
I made a local build without #1037 (3087c4a427853542b80ee6dda8ac59a3f0f7718f) and then the bundles seem to be properly starting.
When I create a local build with #1037 (b9d9135771c030bf34c60ecd4f92ec213606cf50) those bundles remain in the waiting state.

**Comment by cweitkamp** [comment]
I somehow expected that. The most reasonable cause is the change in [(https://github.com/openhab/openhab-core/pull/1037/files#diff-6fdaab327c9f6d25cb978b8feae84522)

**Comment by wborn** [comment]
Yes changing it back seems to fix the issue. 

The `DelegatedSchedulerImpl` would inject itself because it's the only one under which the `Scheduler` interface is registered:

https://github.com/openhab/openhab-core/blob/b48f1c1925cb77664615e11470458b1dae2ac09b/bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/internal/scheduler/DelegatedSchedulerImpl.java#L39-L41

The scheduler the `DelegatedSchedulerImpl` is delegating to is registered as `SchedulerImpl`:

https://github.com/openhab/openhab-core/blob/b48f1c1925cb77664615e11470458b1dae2ac09b/bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/internal/scheduler/SchedulerImpl.java#L49-L51

**Comment by lolodomo** [comment]
After compiling the PR, updating the bundle org.openhab.core and restarting OH, I can confirm I have no more bundles in waiting state and my items are now restored as startup.
Thank you guys.
