### ISSUE TITLE
Replace jetty-http-client with JDK http-client

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab-core#1313]
Since JDK11 a http-client is part of the standard library. The interface looks similar to what jetty provides (except CompletabeFutures instead of callbacks for async requests). 

I would suggest to change from jetty to JDK for OH3. WDYT?

**Comment by wborn** [comment]
I haven't used it yet but it seems to have a nice feature set after I got a short [introduction](https://openjdk.java.net/groups/net/httpclient/intro.html). :-)

**Comment by kaikreuzer** [comment]
I agree that it should probably become our recommendation to use.
I wouldn't necessarily ask everyone to replace Jetty though - since we anyhow have Jetty server as part of the distro, we can keep the Jetty client for the existing bindings that use it, so that they do not have to be refactored (again).

**Comment by J-N-K** [comment]
I can try to figure that out within the tr064 binding. But the questions is: We currently have a shared client from a factory in core. Without messing up the core interface, How shall we create such a shared client if there is no such factory? Or is it enough to hava a shared client per binding?

**Comment by kaikreuzer** [comment]
Good question, I would need to have a deeper look at the Java 11 client how it handles its thread pools. Does it make sense to have a shared client for this one? Then we would have to change the factory in the core, which would indeed be a breaking change - maybe we could still offer a deprecated method to ask for the shared Jetty client, so that the only required refactoring in existing bindings would be a change of the method name.

**Comment by J-N-K** [comment]
I have tried to do it with the new client: https://github.com/J-N-K/openhab2-addons/pull/5/files. It's pretty much the same as before (except that the new client is not support digest authentication out-of-the-box).

**Comment by J-N-K** [comment]
I'll close that for now. The client has some nice features but I think it is not worth reworking existing bindings, it offers no advantage over jetty (except a missing dependency).
