### ISSUE TITLE
[persistence] averageSince shouldn't return null

### ISSUE THREAD

**Issue by 5iver** [openhab/openhab-core#1333]
The JavaDoc says that the Items state will be returned if it has not changed since the DateTime specified, [but it returns null](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.model.persistence/src/org/openhab/core/model/persistence/extensions/PersistenceExtensions.java#L468). This should be changed. Changing the docs would be easy, but I think this would be better functionality.

**Comment by cweitkamp** [comment]
To find an answer why `null` is returned you have to dive into this discussion: https://github.com/eclipse/smarthome/pull/2405

As the calculation considers the current value - if known - imo it would make sense to return the current value instead. Maybe @J-N-K can elaborate on this topic.

I think we have to change the JavaDocs anyway because the other method says to return `null` if no default persistence service is available which is not the case either:
https://github.com/openhab/openhab-core/blob/2c8de4923138f31e1cccf6cd6996ed54a990903d/bundles/org.openhab.core.model.persistence/src/org/openhab/core/model/persistence/extensions/PersistenceExtensions.java#L400-L403

**Comment by J-N-K** [comment]
The problem with returning the current value is that this might be wrong. The calculation is essentially the integral of values over time `\int_{t0}^{now} y(t) dt` divided by the timespan `t0-now`. If we don't have at least two values (one stored and the current value), we can't calculate the average. I'm not convinced that returning the current state is the correct thing to do in that case.

**Comment by J-N-K** [comment]
I re-read the old discussion on ESH and I think the consensus reached is still valid. I'll adjust the JavaDoc.
