### ISSUE TITLE
Channel group 'advanced' property not forwarded to UIs

### ISSUE THREAD

**Issue by pacive** [openhab/openhab-core#1402]
When creating channel group types, ether through XML files or in the binding, you can choose to mark is as advanced, e.g:
```xml
<channel-group-type id="default" advanced="true">
```
However, this property is not forwarded to UIs via the REST API where the thing-type model looks like:

```json
  "channelGroups": [
    {
      "id": "string",
      "description": "string",
      "label": "string",
      "channels": [
      ]
    }
  ],
```
I don't know if any UIs currently uses the property, but I think it should be available for any new admin UI in OH3.

Is it just in the `ChannelGroupDefinitionDTO` it needs to be added? (I noticed there aren't any `ChannelGroupTypeDTO` like there is for the other types, should it be added as well?) Or are there any other parts where it needs to be added? If I can get some pointers I might come up with a PR myself, unless there are many other parts that gets affected.

Edit: Found it's use in org.openhab.core.io.rest.core.internal.thing.ThingTypeResource, which would have to be adapted as well.

**Comment by kaikreuzer** [comment]
I am actually not really clear on why this flag exists at all on channel group types. After all, a channel group can contain advanced and standard channels, so the decision whether a UI shows this group or not should depend on whether or not there are standard channels.
I'd therefore think we could completely remove this flag.
@ghys As you are creating the new UI, what's your view on this?

**Comment by ghys** [comment]
@kaikreuzer I agree with you, it would be clearer if the advanced flag were only in one place - the channels - and you can easily make an advanced group by flagging all of its channels as advanced. So there wouldn't be cases of an advanced group with both advanced and non-advanced channels, which is illogical.
Currently I think the new UI will still display a group label header even if there's no channels to display (because they're all advanced and the "show advanced" box is not checked) but it can be fixed easily.

**Comment by cweitkamp** [comment]
Should we removed the `advanced` attribute for channel group types from XSD and API?

**Comment by kaikreuzer** [comment]
Yes, I'd say so. As it is an incompatible XSD change, we might have to eventually increase the schema version...?

**Comment by cweitkamp** [comment]
See https://github.com/openhab/openhab-core/pull/1410#issue-399500380
