### ISSUE TITLE
[rest] Add ability to add tags to unmanaged Items

### ISSUE THREAD

**Issue by 5iver** [openhab/openhab-core#1447]
Currently, [tags cannot be changed through the REST API for unmanaged Items](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java#L494-497). However, you can add/change/remove tags for unmanaged Items through the console, DSL rules, scripted automation, etc.

**Comment by lolodomo** [comment]
The console commands apparently only allows to update managed items too.

https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.io.console/src/main/java/org/openhab/core/io/console/internal/extension/ItemConsoleCommandExtension.java#L134

**Comment by J-N-K** [comment]
IMO the bug is that it is possible to add metadata for unmanaged items. Imagine metadata for the same scope is added via UI (and thus stored in the JSON database) and later via the .items file where the item is defined. Which one should be used? Also it's very confusing that for one item there could be editable/removable metadata (provided by the `ManagedMetaDataProvider`) and fixed metadata (provided by the file).

Also the code in the `ItemRegistry` supports this, managed metadata is only removed for managed items.

```
    public void removed(Provider<Item> provider, Item element) {
        super.removed(provider, element);
        for (RegistryHook<Item> registryHook : registryHooks) {
            registryHook.afterRemoving(element);
        }
        if (provider instanceof ManagedItemProvider) {
            // remove our metadata for that item
            logger.debug("Item {} was removed, trying to clean up corresponding metadata", element.getUID());
            metadataRegistry.removeItemMetadata(element.getName());
        }
    }
```

So in my opinion the `MetadataRegistry` needs to be fixed so that metadata is only added for managed items.

**Comment by lolodomo** [comment]
IMHO we should not remove any feature regarding configuration through files. Configuring in files probably remains the preferred option for any advanced user.

**Comment by J-N-K** [comment]
The can still add tags from the config file, I'm not talking about removing tags from unmanaged items, just from removing adding managed tags to unmanaged items.

**Comment by spacemanspiff2007** [comment]
> The can still add tags from the config file, I'm not talking about removing tags from unmanaged items, just from removing adding managed tags to unmanaged items.

This is the way!

> I used to have my Items in .items files and had an "override" metadata defined on some Items. When the .items file was loaded it will set that flag to what's in the .items file. However, I'd have some rules that would later change the value of those flags based on some conditions.

But that reads just like a bug and not like a use case:
You can change something when you explicitly define that it should have a constant value.

> But that is a different issue.

Indeed and as you can guess I have a strong opinion on where and how metadata should be modeled at 😉

**Comment by lolodomo** [comment]
> and tags are - as you correctly pointed out - are stored in the item registry. I wonder how adding tags to unmanaged items would work. The console and the REST API prevent it, so it could probably be done by some weird code.

I hope I understand well what we are talking about. Here is an example on how adding tags to unmanaged items:
```
Dimmer LampePerron "Lumière extérieur [%d %%]" <light> [ "Control", "Light" ] { ga="Light" [ name="Lumière à l'extérieur" ], channel="xxx" }
```
In this example, tags "Light" and "Control" are added to the item.
You also have metadata for Google Assistant added to the item in this case.

**Comment by rkoshak** [comment]
Yes, metadata and tags are two different things. It's possible to add metadata to an Item for an unmanaged Item because the metadata is stored and maintained in its own separate registry.

Tags, on the other hand, are stored with the Item in the ItemRegistry.  To be able to add tags through the API for an unmanaged Item someone would need to figure out how to modify an Item defined in a .items file through the API which raises all sorts of problems I think (e.g. how does that become persisted? what happens if new tags are added to the Item's definition in the text file?, etc).

**Comment by lolodomo** [comment]
.items, .things and all files in conf folders are considered as read only files by the OH system. They must be e updated only by the user. 
One of the advantage of these config files over UI files is that they cannot be "corrupted" by the software.

**Comment by spacemanspiff2007** [comment]
@lolodomo :
JNK was talking about adding tags through the gui to an item from an `*.items` file.
That should not be possible (target behavior) and openhab should issue an error message (to be investigated).

Of course adding tags through the definition in the `*.items` file still works and shall continue to work in the future.
You made an example how it's done.

**Comment by J-N-K** [comment]
Having managed tags on unmanaged items would be a complete change in the way managed/unmanaged objects are handled. Currently managed objects can be changed via REST API, unmanaged objects only by changing the file where the object is defined. Tags are clearly associated with items, they are provided by the same provider. Mixing managed/unmanaged items will cause great confusion.
