### ISSUE TITLE
[REST-API] Update item state via GET request

### ISSUE THREAD

**Issue by t2000** [openhab/openhab-core#1489]
Hello,

seeing very old requests like these:

https://community.openhab.org/t/toggle-a-swirtch-via-rest-api/4648

https://community.openhab.org/t/how-to-change-an-openhab-switch-with-http-commands/35063

made me wonder why openHAB doesn't offer a GET method to update the state of an item.

There are various devices out there which cannot be changed, due to a fixed firmware by the vendor or whatever other reasons.

I myself own a doorbell that is able to fire HTTP GET requests if someone rings. There is no way to change this into a POST.

it would be very nice and neat in openHAB to just have a GET REST endpoint to update the sate of an item instead of doing something like this which has been recommended in the community:

https://community.openhab.org/t/how-to-change-an-openhab-switch-with-http-commands/35063/8
https://community.openhab.org/t/use-rest-get-as-a-trigger/78880/2

The classicui will be removed off soon and thus it is not an option to be used.

And external proxy hack looks even more ugly:

https://community.openhab.org/t/how-to-change-an-openhab-switch-with-http-commands/35063/9

Then I gave the static content service from openHAB a try:

https://community.openhab.org/t/use-rest-get-as-a-trigger/78880/3

However, if I place some javascript in there that executes a POST request, it seems that my doorbell does not support executing that javascript at all. If I open it in a browser instead, the POST request fires and my item gets updated.

Thus I am wondering if we can provide another method in:

https://github.com/openhab/openhab-core/blob/53a749f8692d2004f3e876abe433bffbfc1035dc/bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java#L275-L309

that accepts the item stats via a GET request.

I am willing to provide the PR for this if there is a chance that it will get accepted.

I am asking here because I don't know whether there was a reason for not offering this GET endpoint, as the requests have been there 5 years ago already.

For now I have to use the most ugliest workaround: Setup a webserver that executes a bash script with a curl command to execute the POST request against openHAB. Unfortunately this has a great potential to fail in various ways :(

**Comment by jswim788** [comment]
I use nodejs to transform various requests (POST and GET) into the correct form needed by OH.  I don't have complete control over the sending device, so I wouldn't necessarily be able to use a specific GET function if it were added to OH.  I think you'd want to add more generic functionality if you did this.  But then is it worth replicating what is already in nodejs?  I admit it would be nice to have this packaged directly in OH somehow as it would be cleaner for users.

Some samples:
https://community.openhab.org/t/request-binding-for-purpleair-air-quality-sensors/74785/2
https://community.openhab.org/t/new-binding-rainforest-eagle-200-local-binding/44448/73

**Comment by kaikreuzer** [comment]
> why openHAB doesn't offer a GET method to update the state of an item

There's a very simple reason: Because it is openHAB's REST API and and doing state changes upon GET requests is against all REST principles. 
I do not see any reason to have a buggy REST implementation in openHAB, just because some crappy devices out there have some crappy firmware.

I would in any case agree with @jswim788 that such an addition would not address all potential scenarios anyhow as you might also want to map the payload. The way to make external devices interact with openHAB (following "their" way of interaction and not openHAB's way) is through add-ons, in this case either a binding or an IO-add-on (which can implement bring specific HTTP endpoints on openHAB side). Maybe a solution could be to build an HTTP-IO-add-on, which could be configured by the user to provide dedicated urls with configurable processing of payloads and mapping to items.

But for openhab-core, I definitely won't allow adding hacks to the REST API, sorry!

**Comment by t2000** [comment]
Thanks Kai!

I almost thought that you won't accept the changes to the REST API :)

However, you made a very good suggestion how this could be added as an HTTP-IO-add-on. I will think about it and if my workaround bothers me too much, I might give it a shot :)
