### ISSUE TITLE
REST API: /items/{itemName}/state returns RawTypes as encoded plain text

### ISSUE THREAD

**Issue by ghys** [openhab/openhab-core#1581]
Currently when using the `/items/{itemName}/state` to retrieve the state of a RawType (for instance ImageType) we get the base64-encoded version with a `Content-type: text/plain` response header like so:

```
$ http http://localhost:8080/rest/items/Spotify_AlbumImage/state
HTTP/1.1 200 OK
Content-Type: text/plain
Date: Sun, 09 Aug 2020 13:48:35 GMT
Server: Jetty(9.4.20.v20190813)
Transfer-Encoding: chunked

data:image/jpeg;base64,/9j/4AAQSkZJRgAB...
```

This is quite inefficient for images, especially when they change often; I wonder if anything prevents outputting the binary content with the MIME type set in the `Content-Type` HTTP header (if known, otherwise maybe `application/octet-stream`) i.e. something like:

```
$ http http://localhost:8080/rest/items/Spotify_AlbumImage/state
HTTP/1.1 200 OK
Content-Type: image/jpeg <<< *RawType MIME type here*
Date: Sun, 09 Aug 2020 13:48:35 GMT
Server: Jetty(9.4.20.v20190813)

<image bytes>
```

This would I think allow a web UI to display an Image item with a simple:
```html
<img src="/rest/items/Spotify_AlbumImage/state">
```
This is API-breaking, but there could be a way to make it it controllable so that there's no breakage, with a query parameter or the `Accept` header?

**Comment by kaikreuzer** [comment]
I think we use `text/plain` because this is the very same for any item type - and it should be able to feed the result e.g. to the `TypeParser`, which should be able to reconstruct the item state from it.

I'd hence say that we should not change the default content type.
I see your point, though, and I guess it should be no problem to react on an `Accept` header and deliver the MIME type of the RawType instead.
