### ISSUE TITLE
Issues in Ephemeric Settings

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab-core#1663]
Tested with Chrome Browser on Windows 10 with german language):

Strange order of the country list:
![image](https://user-images.githubusercontent.com/616792/93812908-8fe6b200-fc52-11ea-9bb2-58bdb95545b8.png)

At first I thought the list was sorted backwards, but it looks like a random order.

The same happens in the "Region" selection list:
![image](https://user-images.githubusercontent.com/616792/93813171-fd92de00-fc52-11ea-9a8a-971955a5ba01.png)

BTW: both list have on empty entry at the beginning.

**Comment by kaikreuzer** [comment]
Done.

**Comment by wborn** [comment]
Shouldn't sorting these options be done in the frontend? I remember creating PRs for sorting in the backend and then was asked to do it in the frontend. :thinking: If it is done in the backend you'd also end up with sorting options being added to API calls.

**Comment by ghys** [comment]
I think it's best to leave the ordering to the source, in case the order is important you don't want the frontend to mess with it... See https://github.com/openhab/openhab-addons/pull/8517.

**Comment by wborn** [comment]
OK that explains. But probably some lists will look less ordered now because of depending on the backend doing the sorting. Adding some sorting property to configurations parameters could help with that. If there is a configuration parameter with a big list options, it will show different labels depending on the locale making it hard to navigate when not properly sorted.
