### ISSUE TITLE
Allow add-ons in UIs to be filtered on country

### ISSUE THREAD

**Issue by clinique** [openhab/openhab-core#1701]
Would it be a possible option to tag binding accordingly when they are related to a service available only in specific countries, so the user could be presented with services of his country, or by default excluded other country specific bindings ?
A specific tag in the binding.xml file could be used ?

**Comment by wborn** [comment]
If it were implemented to allow for filtering the available add-ons list in the UI the binding.xml file cannot be used because the data in that file will only be available when the Karaf feature is installed. We'd probably also want to add such metadata to any type of add-on and not just bindings. 

It doesn't look like Karaf features support metadata. That's probably also the reason why the add-ons have to follow a certain naming scheme where the add-on type is added to the feature name.

**Comment by clinique** [comment]
Would you have an idea where we could put such an information in the existing schema ?
I thought to binding.xml because the UI is able to grab binding name and description - and the [xsd](https://openhab.org/schemas/binding-1.0.0.xsd) if proper to openhab - or maybe I did not get clearly your point.

**Comment by wborn** [comment]
All the data you see in the UI when installing add-ons is based on the `feature.xml` files.
See the netatmo [feature.xml](https://github.com/openhab/openhab-addons/blob/782a4210a4d8dcc68512d9cfe1f3fe7634adea29/bundles/org.openhab.binding.netatmo/src/main/feature/feature.xml#L5) file.

You can see the same info on the Karaf console using `feature:list | grep 'openhab-'`

When you install an add-on you in fact install a Karaf feature which consists of a set of bundles and possible feature dependencies. Only after the feature has been installed, the bundles are installed and openHAB can read files such as `binding.xml`

So the only way to have all this data available for all add-ons (without first installing them) is by adding it in some way to the `feature.xml` files.

I would not add more of such data to the feature names because that would currently break existing installations. But maybe we can find another way to add more metadata to features. Perhaps there's already a request for adding such metadata to features in the Karaf [issue tracker](https://issues.apache.org/jira/projects/KARAF/issues/).

**Comment by clinique** [comment]
Thanks for the clarification, now I understand better !

**Comment by kaikreuzer** [comment]
I remember that we had an issue about adding all sorts of additional add-on metadata in a separate file (but I just failed finding that issue/discussion 🙄). This was mainly meant to allow filtering on the documentation website (e.g. "cloudbased" vs. "local" and stuff like that, so I think a "country-specific" info could fit in that as well). I would think that such "extended filtering" should be good enough to have on our website as this is where people are more likely browse through what is available. Wdyt? Does anybody remember that issue (@Confectrician maybe) and find its reference?

**Comment by Confectrician** [comment]
> Does anybody remember that issue (@Confectrician maybe) and find its reference?

Late to join the party @kaikreuzer but i think you are looking for this one:
https://github.com/eclipse-archived/smarthome/issues/4503

**Comment by kaikreuzer** [comment]
@clinique I have created https://github.com/openhab/openhab-core/issues/2058 as a follow-up and included a `countries` field in there. I'm not perfectly sure that a flat list works out or if we have situations where we'd rather want to define continents or bigger regions - or maybe do a blacklist to just exclude some countries. If you have concrete add-ons in mind and want to share some details of what definition might make most sense, please feel free to comment there!
