### ISSUE TITLE
openhab --help console command missing

### ISSUE THREAD

**Issue by ghys** [openhab/openhab-core#1715]
I noticed typing `openhab --help` in the console, or `help openhab` doesn't output anything.
`openhab:help` works though.
I don't remember if that were the case with the former `smarthome` command scope.

**Comment by kaikreuzer** [comment]
I don't think this has ever worked.
It seems to be in line with some other commands, though:
```
openhab> cm --help
openhab> help cm
```
I just tried to analyze what might need to be added, but interestingly the `CommandWrapper` is never called by Karaf for those commands. Maybe it is not correct that `name = "help"` is specified, but I haven't found any documentation on how to actually correctly do it in Karaf.

**Comment by J-N-K** [comment]
I had a look at this yesterday and made an interesting observation: if I change the scope to `openhabx` (or others different from `openhab`) and add a proper `Karaf-Commands` entry to the manifest, it works. I didn’t find out yet what is the difference between `openhab` and `openhabx` as scope name. It is clearly not the other command in the `org.openhab.core.karaf` bundle, that also does not work and starts to work when the scope is changed.

**Comment by J-N-K** [comment]
Ok. Figured it out. The issue is that two bundles provide in the same scope. IMO this is a bug in Karaf, because the `ShellHelpProvider` correctly determines all commands for the scope (by looking at `command.startsWith(scope)` and then discards the result if they are spread over more than one bundle. But that's debatable.

So it is not possible to have scopes starting with or equal to `openhab` in two bundles (which we currently have, in `org.openhab.core.karaf` for the `install-service` command and in `org.openhab.core.io.console.karaf` for the other commands.

**Comment by kaikreuzer** [comment]
Great, thanks for the analysis!
