### ISSUE TITLE
rrd4j persistence is installed when no persistence is defined in addons.cfg

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab-core#1741]
I'm trying to set up a minimal system and don't care about persisting state across reboots.  In `addons.cfg` I have:

```
package        = minimal
binding        = astro,ecobee,insteon,netatmo
misc           = openhabcloud
transformation = map
```
and `rrd4j `is also getting installed, even though I didn't configure it to be installed.

**Comment by kaikreuzer** [comment]
OH3 expects persistence to be there and it has been a major issue for OH2 users to figure out how to get started with it.
For this reason, rrd4j is installed and active by default and on purpose, if nothing else is configured.

If you specify in your addons.cfg that you want to use something else, you should add the line
```
persistence =
```
because otherwise you are not making any statement on what persistence you want and thus the default is applied.

**Comment by kaikreuzer** [comment]
To clarify even more: "when no persistence is defined in addons.cfg" is something differrent than saying "when it is defined in addons.cfg that no persistence service should be installed".
