### ISSUE TITLE
Unable to log in with reverse proxy basic authentication

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab-core#1743]
After updating to the latest 3.0.0-SNAPSHOT, I'm unable to log in with a authenticated NGINX reverse proxy using basic authorization.  The log file contains:

```
2020-10-20 07:32:11.845 [WARN ] [ore.io.rest.auth.internal.AuthFilter] - Unauthorized API request: Basic authentication is not allowed
```
NGINX is configured to pass in the` X-OPENHAB-AUTH-HEADER` header as discussed in https://community.openhab.org/t/oh3-with-nginx-reverse-proxy-and-authentication/106528

Enabling basic authentication is a work around, but  this requires the same username/password to be used for both NGINX and OH3.

**Comment by ghys** [comment]
I think what happens is that NGINX will forward its own Basic auth credentials to openHAB (which is bad actually, since they will be likely transmitted in clear text), previously it had no effect because it simply ignored it, but now with #1713 openHAB will think it's meant for it and try to parse them.

Try adding this:
```
proxy_set_header Authorization "";
```
This will remove the Authorization header from the request before passing it to openHAB.
(Reference: https://stackoverflow.com/questions/29644744/hide-a-client-request-header-with-a-nginx-reverse-proxy-server)

**Comment by robnielsen** [comment]
@ghys, I did try that but it didn't work. It caused the login dialog to continually pop up.

**Comment by robnielsen** [comment]
Thanks @ghys, that worked. I originally tried:

`add_header Authorization "";`

Which didn't work

**Comment by ghys** [comment]
Mh, ok. Currently the Authorization header has priority over the X-OPENHAB-TOKEN header but it can be the other way around. It would solve the problem. I'm currently working on that code in #1735, I'll add it to this one.

**Comment by robnielsen** [comment]
> Currently the Authorization header has priority over the X-OPENHAB-TOKEN header but it can be the other way around.

This would probably be a good idea to swap them around.
