### ISSUE TITLE
[OH3] DSL rules can appear in double

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#1808]
In OH3, it can occur that my DSL rules appear all in double.
Suppose that my file is named maison.rules. In this case I see one rule for `maison-xx` and one rule for `tmp_maison-xx`.
The trigger for this issue could be when at OH startup a new bionding is installed. But I am not absolutely sure as I only got this issue 2 or 3 times.

If I restart OH, the rules are no more in double.

**Comment by thewiep** [comment]
I also noticed this once yesterday after I upgraded from M2 to latest snapshot.
After restarting openHAB the tmp_ versions are no longer present.
It didn't seem to happen on M2 though.

**Comment by lolodomo** [comment]
I am not able to find a way to reproduce. And you? Any idea what could be the trigger? 
I only notice that bug 2 or 3 times, that is not a lot considering how many times I started OH3.

**Comment by seimenb** [comment]
I had the same problem today. 
On of my rules was doubled with an tmp_ prefix.
Restarting openHab has not resolved it for me. The doubled rule still showed up after restarting.
Finaly I stopped openHab, copyied the doubling rule file away and startet openHab without the rule file.
Then I adde the rule file again to the rules folder, while openHab was running. 
Since then the rule shows up only ones, as expected. 
And I could start my openHab several times witout doubling the rule again.
