### ISSUE TITLE
startup delay due to lock

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-core#188]
I've been having the problem that to start OH2 on my Pi3 takes VERY long (>30 mins until zwave start initialising). I currently using snapshot 1008, but the problem has been there for a long long time and throughout various versions.
java didn't seem to do anything really at times. Now stracing the java process, I noticed it's accessing the lock file /var/lib/openhab2/tmp/lock over and over, and I also noticed the file was three days old although I had been restarting OH several times in the meantime.
After deleting the tmp dir including the lockfile (and cache dir), startup was MUCH faster. I tried cache deletion earlier, but only that did not make a notable difference.

I had the Pi crash or did kill -9 java at times, that's why the lock file was there.
The point, though, is: why didn't it get deleted on startup?

**Comment by kaikreuzer** [comment]
I would suggest to discuss this in the forum at https://community.openhab.org/.
If a bug is then identified, the best place to file it would be https://github.com/openhab/openhab-distro/issues resp. https://github.com/openhab/openhab-linuxpkg/issues in case it turns out to be an APT related bug. Thanks!
