### ISSUE TITLE
Update existing Things for definition changes

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-core#1924]
<a alt="bounty" href="https://www.bountysource.com/issues/95151739"><img src="https://api.bountysource.com/badge/issue?issue_id=95151739"></a>

Currently you have to manually recreate Things for changes in their ThingType or Channel(Group)Definitions to be applied.

The framework should for instance automatically add new channels or configuration parameters.

See also this ESH issue: https://github.com/eclipse-archived/smarthome/issues/2555

These PRs have already been created for solving the issue:

* https://github.com/openhab/openhab-core/pull/1027
* https://github.com/openhab/openhab-core/pull/628
* https://github.com/openhab/openhab-core/pull/527
* https://github.com/eclipse-archived/smarthome/pull/6537

**Comment by wborn** [comment]
As discussed I've added your awarded bounty for #888 on this issue @J-N-K. :+1:

**Comment by J-N-K** [comment]
The biggest problem is that we don't know which channels were originally added from the XML and which channels where added by the user (extensible). This could probably be solved in the REST call when the channel is added. This should be step 1 (and probably should be done before OH3, so that at least all the people starting from scratch will benefit later if we solved the other problems).

We also need to find a solution for already existing things (e.g. MQTT only has extensible channels), a lot of channels would be lost if the flag cannot be added for existing things. This needs to be done during the upgrade process.

The third question is how to handle dynamically added channels. Removing and re-creating them during each startup is possible (and links should be preserved), but this is quite time-consuming and will probably impose bigger delays for larger installations until all things are configured.

Maybe a solution would be to have a field "addedBy" in the channel, which is set to either "framework" (for channels added from the thing defintion) ,"dynamic" (for channels added by the thing handler) and "user" (for channels added by the user).

If these issues are solved, it should be possible to go the route I originally proposed:

- read the stored thing
- create the same thing from scratch
- check which channels (that are not dynamically added and not extensible) are missing in the newly created thing, remove them and add those that are missing
- add (modified) thing to the thingmanager

**Comment by cdjackson** [comment]
Please can you ensure that this can be disabled by bindings (I know we discussed this in the past so I think that was agreed already, but as pointed out, a lot of these discussions were a long time ago now ;) ).

Personally I use different approach - I add a version ID to the thing type, and then use the migrate method to update the thing definition. This ensures there is some control over the process. 

The ZigBee binding does a check on dynamic channels to see if there is a need to change them (ie compare the existing and "new" definition to see if they are the same). It only updates the thing definition if there is a change.

**Comment by J-N-K** [comment]
@cdjackson That (versioned thing-typed) would be by favorite as well. We could add helper methods to the thingbuilder (or handler) to make make that check easier. Unfortunately this was rejected and I don‘t see that this has changed.

**Comment by J-N-K** [comment]
Can we please discuss the "version-number for thing-types" and migratin within the thing handler? It's much easier to implement and also allows for special cases where additional information is needed in the thing handler.

**Comment by edwolfe807** [comment]
Is this going to be fixed for OH3.2? As developer I would never consider putting this type of burden on a user. When an upgrade is done, it should upgrade everything. Especially since there isn't anything documented in the [migration documentation](https://www.openhab.org/docs/configuration/migration/). If everything goes perfect, I may be able to complete with in an hour. However, with 86 things, 481 items and 81 rules, this "issue" may potentially cause me hours (days, weeks) of work/debugging for every upgrade.

**Comment by wborn** [comment]
> Is this going to be fixed for OH3.2?

Probably not because nobody has volunteered working on it and there's just ~1 month left until the release.

> Especially since there isn't anything documented in the migration documentation. 

If you think the docs can be improved, please create PRs for this in [openhab-docs](https://github.com/openhab/openhab-docs).

openHAB is a community driven project so it is only as good as the contributions everybody is willing to make.

**Comment by jlaur** [comment]
See also #2590

**Comment by J-N-K** [comment]
@jlaur I had another look at this today. Seamless "Renaming" is difficult, because it would require to also change the `ItemChannelLink`s, which might not be managed. If you define the thing in UI we can "rename" the channel (essentially remove and add with new name and same configuration), but we can't adjust the links defined in `.items`-files.

**Comment by jlaur** [comment]
@J-N-K - I agree. When you "hardcode" channel names into your `.items` files, you'd expect no one to touch this file, thus you - as an advanced user - is the only one who can do the rename. IMHO this is expected, and users can adjust manually in this case, of course assuming that such renames are still mentioned in the release notes.

Usually file-based users are best off with breaking changes since there is no need to recreate things when definitions have changed slightly, new channels have been added etc. So we should probably keep our focus at getting managed things upgraded/migrated automatically.

**Comment by kaikreuzer** [comment]
> So we should probably keep our focus at getting managed things upgraded/migrated automatically.

We probably have to differentiate between different kinds of updates:

For newly added channels, it should definitely be automatic and also the binding developer should not have to deal with it through any kind of migration logic. This is already the case for textually defined Things and it seemed that with https://github.com/openhab/openhab-core/pull/1027 we were very close to having the same for managed things already.

For renamed channels, existing setups would indeed break and even a migration logic within the binding couldn't really help as this should possibly not be allowed to tinker with links (that's rather a job for the framework, if such an automatic adjustment is desired, knowing that it won't work for textual configurations). So your proposal in https://github.com/openhab/openhab-core/issues/2590 with unlisting channels, but still supporting them (for a while), sounds like a good idea to solve this.

Introducing versioning of thing types might be a valuable information for the framework to know how old the managed things are and what has changed meanwhile - out of this, messages for the user could be compiled and shown in the UI, if there is a breaking change that cannot be automatically migrated (similar to our notices in the distro).

> The biggest problem is that we don't know which channels were originally added from the XML and which channels were added by the user (extensible). 

It should be the ones that are not defined in the XML, but still stored in the database with the thing - if we decide to handle managed things the same way as textual things (which imho has some charme, since we only have to solve all issues once and not twice).

> The third question is how to handle dynamically added channels. Removing and re-creating them during each startup is possible (and links should be preserved), but this is quite time-consuming 

Note that this is what happens for textual things right now for ALL (not only the dynamically added) channels. So I do not really see this as an issue. For managed things, the only reason to store channels with the thing would be the case where the user adds a configuration to a channel (this is again a similar situation for textual things).
