### ISSUE TITLE
OH3.RC2 - All my daily rules (cron trigger) run twice

### ISSUE THREAD

**Issue by moodyblue** [openhab/openhab-core#1976]
See https://community.openhab.org/t/openhab-3-0-release-candidates-discussion/110200/184?u=moody_blue

**Comment by Hilbrand** [comment]
This is not oh3 specific,but has been reported earlier. But no one filed a proper clear issue here with specific details. https://community.openhab.org/t/cron-triggered-rules-are-executed-twice/80321

**Comment by jewesta** [comment]
@moodyblue I’m facing the same issue with a weekly rule. OpenHAB is giving my kids twice the amount of pocket money every week and this has to stop! 😉 I wanted to try and reproduce it tomorrow with a more practical interval. Before I start experiments I wanted to ask: Could you please post your cron schedule? Thanks!

**Comment by moodyblue** [comment]
Here is a cron schedule that executes twice `Time cron "0 0 8 ? * * *"`

**Comment by jewesta** [comment]
Apologies for the delay. Christmas and all that entails got in the way. :-)

Did some experiments with various intervals and to no one's surprise cannot reproduce the issue with test rules. :-/ I have set up some longer running rules and will post my results once they have fired. I am also beginning to suspect that the rule in question may somehow exists twice. This is just speculation. But I have had rare issues with "phantom" items (etc.) before that hadn't gotten "deregistered" somehow. Who knows -- maybe the rule (for some reason) exists twice internally?

I will try to find out more about this. In the meantime I have renamed the rule that fires twice and added a debug message to be printed. Since it fires once per week on a Friday it will take at least until next weekend before I can report back.

**Comment by jewesta** [comment]
It's Friday and my test rules have fired. Unfortunately all of them were executed twice. That includes the rule that already existed (and got renamed to crontest003) and the rules that I created new in a separate .rules file (crontest001 and crontest002). Here's how the simplest of the rules looks like:

```
rule "crontest001"
when
    Time cron "0 0 12 ? * FRI" //Every Friday at 12
then
    logError("crontest001", "This should be printed every Friday at 12.")
end
```

The cron condition is exactly identical in all three rules and there are no other conditions present in the "when" section. Here's what got logged on the console:

```
2021-01-15 11:59:47.432 [ERROR] [penhab.core.model.script.crontest003] - This should be printed every Friday at 12.
2021-01-15 11:59:47.474 [ERROR] [penhab.core.model.script.crontest001] - This should be printed every Friday at 12.
2021-01-15 11:59:47.475 [ERROR] [penhab.core.model.script.crontest004] - This should be printed every Friday at 12.
2021-01-15 12:00:00.441 [ERROR] [penhab.core.model.script.crontest003] - This should be printed every Friday at 12.
2021-01-15 12:00:00.480 [ERROR] [penhab.core.model.script.crontest004] - This should be printed every Friday at 12.
2021-01-15 12:00:00.480 [ERROR] [penhab.core.model.script.crontest001] - This should be printed every Friday at 12.
```

As can be seen the rules fire almost exactly three seconds prematurely and then again on time.

I set up another rule that will fire on Sunday where I'm obviously still waiting for a result.

**Comment by jewesta** [comment]
Just a thought (and I have no idea how cron executed rules actually work in openHAB): Could there be a rounding error at play due to decimal vs. binary storage of Float/Decimal values in Java? I am just writing this because if e.g. milliseconds since epoch would be stored in a Float or Double type there could be situations where the result jumps back and forth even though values are being added only. I know this is a very basic concept but maybe it happens indirectly or it happening is not directly obvious. Again - just a random thought.

**Comment by Hilbrand** [comment]
@jewesta what hardware/os are you running? It's likely an inaccurate clock problem of the underlying system. Time is stored as long, so very unlikely an rounding problem.

**Comment by jewesta** [comment]
@Hilbrand I’m running openHAB on macOS. @moodyblue what system are you on?

**Comment by moodyblue** [comment]
I'm running OH3 natively in a QNAP NAS (intel Celeron).

**Comment by jewesta** [comment]
Apologies if this is not relevant. Just tossing around some ideas, because I had some issues with Java scheduling before.

Does openHAB use the SchedulesExecutorServie? I’m asking because there can be problems with [time drift](https://stackoverflow.com/a/56598273/14667781). Suppose (for whatever reason) the scheduler is a tiny bit slow and fires a couple of nanoseconds after(!) the event. In my case very shortly after Friday at noon. It would then be rescheduled for the next event, which would be one week ahead. No problem.

Now suppose (again, for whatever reason) the scheduler is fast and fires very briefly before the event is actually supposed to happen. It would then fire a tiny bit too early. Which wouldn’t be a problem in itself. But suppose it would then be rescheduled for the next occurrence. Which in my case would be three seconds ahead. It would then fire again, perfectly on time (because there was not enough time to acquire drift errors) and then be rescheduled again.

**Comment by ananchev** [comment]
I believe I am facing the same behaviour on OH3.0.1
Rules and persistence are executed twice, first time prematurely. 
Any cron trigger for period more than every five minutes (e.g. 0 0/30 * * * ?) leads to this issue.
Example persistence:
`2021-03-29 18:29:37.447 [TRACE] [persistence.internal.PersistItemsJob] - Storing item 'l2Reg00' with persistence service 'influxdb' took 0ms

2021-03-29 18:30:00.450 [TRACE] [persistence.internal.PersistItemsJob] - Storing item 'l2Reg00' with persistence service 'influxdb' took 0ms`

Example cron rule:
`2021-03-29 18:49:57.985 [INFO ] [org.openhab.core.model.script.ENERGY] - ten minutes have passed...

2021-03-29 18:50:00.991 [INFO ] [org.openhab.core.model.script.ENERGY] - ten minutes have passed...`

**Comment by jewesta** [comment]
Hope it is OK to comment on this closed issue: VERY happy to announce that this resolved the issue for me. THANK YOU very much @Hilbrand for all your efforts! 🙏
