### ISSUE TITLE
Openhab 3  Gui link to Frontail is wrong

### ISSUE THREAD

**Issue by Rar9** [openhab/openhab-core#2128]
The GUI OpenHab3 LINK for frontail is wrong if  IP4 + IP6 are used.

The link to Frontail is listing both <a href="ip4ip6:9001" which is wrong.

It should be either <a href="ip4:9001 > or <a href="ip6:9001 > only.

**Comment by ecdye** [comment]
@Rar9 This is an openhabian problem and should be raised in its repository.

**Comment by Rar9** [comment]
Can you moved it there?

**Comment by ecdye** [comment]
I cannot, I do not have access to transfer issues. @kaikreuzer Can you transfer this to openhabian?

**Comment by cweitkamp** [comment]
Closing this for now. Please reopen the issue in https://github.com/openhab/openhabian/issues. Thanks.

**Comment by ecdye** [comment]
Should be fine as I have already fixed it.

**Comment by sascha777** [comment]
I just migrated to OH3 on a second test system that I used to adjust rules and items to the new structure.

After all the migration tasks I backuped the test system and restored the config on my primary OH3 system.
Everything is working properly except the frontail link from the MainUI. This is still pointing to my test system.

Frontail is installed on my primary OH3 and I can open it via ip:9001, so it is just the link pointing to the wrong system.
Could that be due to the import of the transferred config backup?

If so, is there a place where I can manually change the link to the right url? I checked in the runtime.cfg but frontail isn't listed there.
