### ISSUE TITLE
For channel-based triggers, can no longer extract the channel which triggered the event using the receivedEvent implicit variable

### ISSUE THREAD

**Issue by lukiep111** [openhab/openhab-core#2143]
In OH2.x the receivedEvent implicit variable allowed the ability to extract the name of the channel which triggered the event

ie: I have a rule which triggers at dusk and includes the line ```val trigger = receivedEvent.getChannel().toString()```.
val gets returned as: ```astro:sun:home:civilDusk#event```.

In OH3 the way the implicit variable works has changed, and it seems we have lost the ability to get to the name of the channel.  For what it's worth the error is ```‘getChannel’ is not a member of ‘java.lang.String’```. I'm not sure if this would be considered a regression. 

Maybe a solution might be a new implicit variable called triggeringChannel?

**Comment by RobZe89** [comment]
Is there a workaround or some progress?

**Comment by markus7017** [comment]
@cweitkamp any update on this topic? Having something like triggeredChannel (compared to triggeredItem) makes it easy to have one rule covering a group of devices, otherwise I need to duplicate the trigger rule per device or some other mechanism to check all devices even a single one triggered an event/alarm

**Comment by cweitkamp** [comment]
@markus7017 Maybe this draft will help: https://github.com/openhab/openhab-core/pull/2567.

Can you check it?
