### ISSUE TITLE
group averge issues when mixing z-wave and mqtt items

### ISSUE THREAD

**Issue by mdeanda** [openhab/openhab-core#2216]
i have a group defined in an items file that contains the humidity item from a zooz 4 in 1 sensor and 2 mqtt  based items.

Group:Number:AVG outsideHumidityGroup "Outside Humidity [%.2f]"

The zwave item is defined as a NumberItem type as are the mqtt items.

I've been trying to get them to both show "humidity" as a percentage (values in the range 0-100) but mqtt items always map the values as "0.65%" when the json input has: {"humidity":"75"} and I use JSONPATH:$.humidity to map the field. The only item type that shows the value correct is the DimmerItem.

I created a test script in oh3's ui with the following to attempt to debug:

```
logInfo("test", String.valueOf(outsideHumidityGroup.state));
logInfo("test", String.valueOf(outsideHumidityGroup.allMembers));
```
and the output i see
```
2021-02-26 22:11:46.119 [INFO ] [org.openhab.core.model.script.test  ] - 9.04666667
2021-02-26 22:11:46.124 [INFO ] [org.openhab.core.model.script.test  ] - [FrontPorch_SensorRelativeHumidity (Type=NumberItem, State=26.6, Label=Porch Humidity, Category=Humidity, Tags=[Measurement, Humidity], Groups=[outsideHumidityGroup]), GarageController_Humidity (Type=NumberItem, State=0.27300000, Label=Humidity, Category=, Tags=[Point], Groups=[outsideHumidityGroup]), GateController_Humidity (Type=NumberItem, State=0.26700000, Label=Gate Humidity [%s], Category=, Tags=[Measurement], Groups=[outsideHumidityGroup])]

```

it appears that the 2 mqtt items are treated as if the value is ".26" instead of 26 so the average gets calculated incorrectly. for this test, i posted the following to my local mosquitto server:

```
-m '{"temperature":"55.04","heat_index":"51.48","dew_point":"21.06","comfort":"Cold And Dry","id":243,"ts":1614325380, "humidity": "26"}'
```

i had previously tried using another transformation to multiply the values by 100 but i couldn't figure out where to save the script

**Comment by Rossko57** [comment]
So the problem is nothing to do with the Group function, but revolves around the unexpected state values in your MQTT Items?

> it appears that the 2 mqtt items are treated as if the value is ".26"

I think you've fallen in the mire of Quantity Types here.
I will bet your zwave channel type is actually number:dimensionless, a quantity type with units, usually %
Your MQTT channel is probably configured without units?

Both linked to plain Number type Item.  Here's a pitfall, the plain Number may have no default units ... but "blank units" happens to be meaningful to a number:dimensionless type, it gets interpreted as meaning ratio or proportion, as in 3:1 
26% in ratio terms is 0.26

But why is conversion being invoked at all?  I think the Group AVG function is doing what it can, when given a collection of Quantities in different units.

**Comment by mdeanda** [comment]
aha! i think your tip helped me solve it. the channel was defined as "dimmer" and i changed it in the code tab to:

```
    channelTypeUID: mqtt:number
```

and it solved the problem.

**Comment by Rossko57** [comment]
Ahh a Dimmer, yes I recall there are drop-downs talking "percent types" that are tempting for humidity but incorrect for that use.

**Comment by Rossko57** [comment]
> it solved the problem.

Can this issue be closed now?

**Comment by mdeanda** [comment]
yeah it solved the problem. i wish it was a little more obvious that dimmers would work this way in that it scales incoming values. i'm sure other would get stuck on that subtle difference.
