### ISSUE TITLE
Laggy/halted interaction on config and rules changes

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-core#231]
Whenever I change an items or rules file, to process this update in OH can take up to 2 or 3 minutes (for a 1k lines rules file on a Pi2).  java is runnning at 100% CPU.
Meanwhile, the interaction via REST or Web UI is apparently STOPPED until the current file is processed.
Can't we have this processing take place in a separate thread ? Or is there some sort of locking on access to internal data, and if so, can this be reworked to be more fine-grained ?

**Comment by lolodomo** [comment]
I can confirm that the handling of a rule change seems to lock the UI.

**Comment by mstormi** [comment]
If you decide to rework this, please also consider processing multiple rules in parallel as sequential processing of many rules takes a long time but we all have multi-core processors nowadays.

**Comment by kaikreuzer** [comment]
I cannot imagine that the REST API is blocked if a file system reload takes place. These are completely independent services. It sounds rather as the 100% CPU load simply makes the whole system sluggish.

So to boil down you issue, it sounds as if you are saying "a rule file with 1000 lines requires 2-3 minutes to be processed". If so, please open an issue at ESH with an example file so that it can be easily reproduced. The example file can probably something that you create by copy&pasting a simple rule many times.

**Comment by mstormi** [comment]
Yes it _is_ locked up (not sure if on API layer or where exactly), and it happens on _any_ rule und items file (re)load, and it takes the UI to react exactly as long as it takes to process the updated file. This cannot be attributed to general system sluggishness as even a Pi2 is a quad-core system and 100% CPU use means that exactly ONE CPU core is busy but three are idling so there's plenty of power to run API and UI. It's that UI or API or whatever down the stack is locked while that file update is processed.
Not sure if there's some jetty or Karaf or whatever specific setting involved but there's none that I'm aware of, and @lolodomo saw it, too.
Either way, as requested, opened ESH #4716
