### ISSUE TITLE
[automation] Pass variables from one rule to a script

### ISSUE THREAD

**Issue by flo-mic** [openhab/openhab-core#2475]
I would like to write generic scripts which can be reused from different rules. For this I would need a possibility to pass variables from the rule to the script. I know the preferred way is to use and item and write/read the state from this. But there are some scenarios where this will not work. E.G. providing objects like timers is not possible within a item. Also If the script is triggered simultaneously from two rules, it may happen that the passed variable from one run is overwritten in the item state before it can run.

**Comment by rkoshak** [comment]
Which language? This is not possible in Rules DSL. But JavaScript and Python support libraries that can be imported. 

For example, in JavaScript, put your library code in $OH_CONF/automation/lib/javascript in a .js file and load it in your rule:

```
var OPENHAB_CONF = java.lang.System.getenv("OPENHAB_CONF");
load(OPENHAB_CONF+'/automation/lib/javascript/community/mylibrary.js');
```
From that point onward everything exposed by mylibrary.js will be available in the rule.

In MainUI developed rules you can also call rule from another rule and pass it data (but you can't get anything back). 

For example, in a JavaScript Script Action in MainUI

```
// Run another rule
var FrameworkUtil = Java.type("org.osgi.framework.FrameworkUtil");
var _bundle = FrameworkUtil.getBundle(scriptExtension.class);
var bundle_context = _bundle.getBundleContext()
var classname = "org.openhab.core.automation.RuleManager"
var RuleManager_Ref = bundle_context.getServiceReference(classname);
var RuleManager = bundle_context.getService(RuleManager_Ref);
RuleManager.runNow("tocall");
var map = new java.util.HashMap();
map.put("test_data", "Passed data to called function!")
RuleManager.runNow("tocall", true, map); // second argument is whether to consider the conditions, third is a Map<String, Object>
```

Note that all of that Framework stuff and interaction with the RuleManager is a great candidate to put into a library. ;-)

Rules DSL is simple by design. If you need more than it offers you need to use one of the many other choices in languages which provide more capabilities.

**Comment by flo-mic** [comment]
@rkoshak great I was not aware of both possibilities. Will give it a try in my rules. Thanks!
