### ISSUE TITLE
Feature: allow enabling authentication for all activities.

### ISSUE THREAD

**Issue by flo-mic** [openhab/openhab-core#2476]
Currently there are a lot activities on the API and WebUI allowed without authentication. There should be a possibility to force a user login before sending API commands or be able to access the WebUI. This feature should be disabled by default for the starting point but configurable from the WebUI so that a paranoid user can enable it if all his applications support the authentication or do not require the API top work.

This feature is especially important as soon you want to integrate a security system within openhab. It does not make sense to control a security system from openhab if I can change the item states without any authentication.

**Comment by ghys** [comment]
This is what you're looking for:

![image](https://user-images.githubusercontent.com/2004147/132105060-b2169910-517b-4ad1-95ef-b72ba72f09e9.png)

You'll find it in Settings > API Security in the UI. It's an advanced option for now because it has the potential to break clients which don't expect authentication.

**Comment by flo-mic** [comment]
ah perfect, I was not aware of this. Next time I will first check if there are any advanced settings. Thank you for the fast response.
