### ISSUE TITLE
Partial use of common registry API forced by UIComponentRegistryFactory

### ISSUE THREAD

**Issue by splatch** [openhab/openhab-core#2513]
Most of openHAB APIs, whether these are things, items or links rely on dedicated `Registry` instance feed by one or more `Provider` services. This design helps to have various sources of core elements managed in various ways.
This is however not reflected within UI registries for pages and widgets since they are wrapped and maintained only via storage.

I believe this is not a major trouble, however current construction does not permit ie. read only UI elements to be present in system. They can't be dynamically computed based on supplied configurations, present items and such.
Changing that would open several fields - ie. where pages could be provided by further system extensions.

**Comment by kaikreuzer** [comment]
You're right, this registry does not really follow the same concept as all the others.
I agree that it would be nice to be able to also provide alternative providers besides the managed one.

**Comment by jpg0** [comment]
@splatch does your code work? No change for existing use-cases, but adds in the ability to register a new provider in osgi?

I ask because I have the same requirements, and am currently hacking it by stuffing new providers into the underlying registry via reflection, which I don't want to be doing.

If your code is good, I'm happy to turn it into a PR (unless you want to)?

**Comment by jpg0** [comment]
@splatch I tried getting this to work however I suspect that I am missing an updated `UIComponentRegistryImpl`?

**Comment by splatch** [comment]
@jpg0 good spot, updated code sample!
