### ISSUE TITLE
Make config description available to things

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab-core#2719]
After enabling config validation in #2682 it was found out that some thing handlers introduced invalid configurations which prevented thing initialization (reported as #2710). While the erroneous updates were prevented by #2712, this still leaves the handler with the task of validating configuration values. 

The `ThingHandlerCallback.validateConfigurationParameters` method can be used to find out if a given configuration is valid but does not allow checking of individual parameters and does not provide a simple way to programmatically check the types/limits of these. 

The `ThingHandlerCallback` has access to the `ConfigDescriptionRegistry` and could provide the `ConfigDescription`s of thing and channel to the handler. The question is if it would be better to allow access to the registry (`ConfigDescriptionRegistry getConfigDescriptionRegistry()`), and let the handler do all the work or if the retrieval based on the URI (`ConfigDescription getConfigDescription(String configDescriptionURI)`) or even the object (thing/channel) would be preferable.

Any thoughts?

**Comment by cweitkamp** [comment]
We removed all services from `BaseThingHandler` a while ago because they should not have access to them by default. Thus I tend to add a `getConfigDescription(URI configDescriptionURI)` method to the callback. This is the flexible solution for bindings to access the configuration description.

On the other hand I am thinking about a different solution. There already is a `validateConfigurationParameters(Map<String, Object>) method which checks given configurationParameters for the thing and throws a `ConfigurationException` in case of violations. Is this a possibilty to solve the requested feature too? We can add an additional method to validate Channel configurations.

**Comment by cdjackson** [comment]
> There already is a validateConfigurationParameters(Map<String, Object>) method which checks given configurationParameters for the thing and throws a ConfigurationException` in case of violations. Is this a possibilty to solve the requested feature too? 

No - throwing an exception after validation doesn't do the same thing as this issue is not about validation - it's about getting the configuration. 

The binding needs to be able to access the actual configuration - not just find out if there's an error with the validation. As an example, I need to be able to find the min/max values for config, so that the data can be processed appropriately. If I get a value of 100 - it will pass validation if the max value is 255 or 127 or 65535, but I need to know what the max value is to allow me to process it.

**Comment by J-N-K** [comment]
I don't like the design of `validateConfigurationParameters`. It throws a `RuntimeException` instead of returning a boolean (which would be better IMO). I did a quick check in openhab-addons and there are seven cases where `validateConfigurationParameters` is used. Only one of these properly catches the exception.

What do you think about marking it `@Deprecated`, and adding a `boolean validateConfigurationParameter(UID typeUid, Map<String, Object> configuration)`. This would allow validating things and channel configurations by their TypeUID. 

This still does not help to get the config description which I think is useful, because it also allows access e.g. to the default value.
