### ISSUE TITLE
DateTime as rule trigger

### ISSUE THREAD

**Issue by mikaelgu80** [openhab/openhab-core#2726]
I'd like to request a new rule trigger, specifically an item of DateTime type. Rule should fire when the time is equal to the one specified in the item.
My use case is that I often set a timer a fair bit in the future and either experience a restart or something else unexpected that causes the timer to reset. Setting an item that's persisted would both simplify the rule and imho make operation more reliable.

Mikael

**Comment by rkoshak** [comment]
There is a rule template in the marketplace that does exactly this.

https://community.openhab.org/t/alarm-clock-rule/127194

**Comment by mikaelgu80** [comment]
That would indeed look to match my needs. I tried it though and it never fires. (tried with 3.2.0 and 3.3.0.M1). Nothing in the logs at the specified run time. My item is DateTime.
When I execute the rule manually I get the error:
"Script execution of rule with UID '86886d6319' failed: TypeError: Cannot read property "class" from undefined in <eval> at line number 30"

**Comment by jimtng** [comment]
There is a TimeOfDay trigger in core. https://community.openhab.org/t/identifying-timeofdaytrigger-within-ecmascript/124899

**Comment by mikaelgu80** [comment]
I ended up creating another rule that runs my original rules when start level reaches 100. Not elegant and not the way it should be IMHO, but it works.

**Comment by rkoshak** [comment]
Please add a reply on the Marketplace entry with details so that the rule template can be fixed. Lots of people are using it successfully so I need lots of details to figure out what's different about your config. But that doesn't belong here. In particular walk through the steps you followed to install the template, instantiate the rule, etc. Note that the rule only runs at startup and when the DateTime Item changes. It creates a timer that calls your supplied rule at that date and time.

**Comment by proggprod** [comment]
How can I use this new feature is DSL rules?

**Comment by J-N-K** [comment]
You can't. I have created #2963 for that.

**Comment by jimtng** [comment]
This also needs to be added to the docs, not just the addition to the DSL rule but in general for GUI / JSR223.

**Comment by J-N-K** [comment]
Documentation done.
