### ISSUE TITLE
Simplify way of loading libraries

### ISSUE THREAD

**Issue by NCC1701M** [openhab/openhab-core#2776]
As described in this [article](https://community.openhab.org/t/oh-3-examples-writing-and-using-javascript-libraries-in-mainui-created-rules/108526) the way of loading a library is

```javascript
this.OPENHAB_CONF = (this.OPENHAB_CONF === undefined) ? java.lang.System.getProperty("openhab.conf") : this.OPENHAB_CONF;
load(OPENHAB_CONF + "/automation/lib/javascript/personal/utils.js")
```

The way a library is loaded could be simplified if the `load` function would handle relative paths.

For example:

If the load function is called like this
```javascript
load("automation/lib/javascript/personal/utils.js");
```

the function could detect that a relative path was provided (on linux because of the missing / at the beginning of the string) and automatically prepend the `OPENHAB_CONF` path.

Otherwise if the function is called with an absolute path 
```javascript
load("/somewhere/on/the/filesystem/automation/lib/javascript/personal/utils.js");
```

it would not prepend the `OPENHAB_CONF`. 

This would make loading libraries a little easier and would lead to better code because DRY (Don't Repeat Yourself).

**Comment by NCC1701M** [comment]
No reaction on this?

**Comment by J-N-K** [comment]
IMO this is depending on the scripting language and needs to be addressed in the respective scripting add-on (if at all). I'm not sure if magically resolving paths is really a good idea.

**Comment by NCC1701M** [comment]
There is no magic. It's a simple algorithm. The system should know best where the configuration folder is

**Comment by rkoshak** [comment]
> As described in this [article](https://community.openhab.org/t/oh-3-examples-writing-and-using-javascript-libraries-in-mainui-created-rules/108526) the way of loading a library is

As the author of that article I think it's worth chiming in here.

That article is for Nashorn ECMAScript 5.1 and *only* applicable to Nashorn ECMAScript 5.1. As far as I know, only Nashorn requires the use of the full path like that. Even the JS Scripting ECMAScript 2021 add-on just requires a simple `const lib = require('name_of_library');`. Jython too imports using relative paths. 

Since Nashorn is going to go away as soon as we move off of JDK 14 anyway, I'm not sure it's worth spending effort on this at this time. But if effort were spent then I agree with @J-N-K, it's something that needs to be handled by the separate automation engines themselves (and in fact already is being handled that way already for all but Nashorn). I do think that Nashorn is handled by openhab-core and not as a separate add-on so this is where it would have to be implemented. 

But that's assuming we can do anything about it. I'm also not certain that openHAB has much ability to control this. That load function and its requirements I think are defined by Nashorn itself. We'd have to create some sort of wrapper which means we'd need to include a helper library to abstract the openHAB stuff to Nashorn JS and implement that in that helper library (which leads to a catch-22 where you need to load a library to make loading libraries easier).

**Comment by NCC1701M** [comment]
> That article is for Nashorn ECMAScript 5.1 and _only_ applicable to Nashorn ECMAScript 5.1. As far as I know, only Nashorn requires the use of the full path like that. 

This was the only article I could found on how to use external scripts. The functionality has to be documented.

>  this is depending on the scripting language and needs to be addressed in the respective scripting add-on

There a a lot of GitHub Repos for openhab. For outsiders it's pretty difficult to tell where to place a request (in this case loading something sounds like a core funtionality). 
There should be a repo or something similar to address such issues and those involved in the project should move them to the corresponding repo

**Comment by J-N-K** [comment]
As I said: this should be handled by the respective add-on.

**Comment by NCC1701M** [comment]
And as I said, for outsiders it is pretty difficult to determine which of those many repos is the correct one and that those people who are working on openhab should move those issues to the correct (AddOn-) repo. 

So instead of only closing this issue, could you please open or move this issue to the correct repo?

Thanks
