### ISSUE TITLE
Mac Safari all edit buttons no longer work  openHAB 3.3.0 Build #2809

### ISSUE THREAD

**Issue by ChR-iSz** [openhab/openhab-core#2850]
I have update openhabian today. Now all widget configure button don't work on MacOS Safari.

<img width="382" alt="Bildschirmfoto 2022-03-18 um 15 03 26" src="https://user-images.githubusercontent.com/49807897/159017371-6d21c41d-ba7c-4a7c-b4e5-d0b66e532042.png">

<img width="1112" alt="Bildschirmfoto 2022-03-18 um 14 59 14" src="https://user-images.githubusercontent.com/49807897/159017007-7d1d5402-0544-4dfc-8374-4512803cc14a.png">

**Comment by J-N-K** [comment]
I cannot reproduce that with Safari Version 15.4 (17613.1.17.1.6) / macOS 12.3 (21E230) / M1.

Is this for all widgets or only some? I tried with the washing machine widget from the marketplace.

**Comment by liviom** [comment]
J-N-K 
The issue isn't related only to safari...
Also windows, linux and android with chrome or edge or Firefox are affected.
The issue is detected from many users in community forum, see
[Here](https://community.openhab.org/t/standard-widget-configuration-popup-doesnt-appear-when-click-on-button-or-configure-icon-menu/134266/2) 
And [Here](https://community.openhab.org/t/cannot-edit-ui-since-3-3-0-2805/134264)

**Comment by ChR-iSz** [comment]
The problem is that I can't configure any widget with the current version. The popup window does not open at all, and in the browser console I only see the above error. See screenshot in my first thread.

can anyone fix this, or can I workaround it myself ?

**Comment by liviom** [comment]
@J-N-K 

![image](https://user-images.githubusercontent.com/13430820/159221736-c8b68986-b858-4f1d-a505-90d552c415b9.png)

**Comment by ChR-iSz** [comment]
Great, working now 👍🏼, but the Listitems buttons (+ Button to add a listitem AND Configure List) still not work.
See #2865
