### ISSUE TITLE
Invalid binding name in addons.cfg causes memory usage to increase continuously

### ISSUE THREAD

**Issue by mhilbush** [openhab/openhab-core#286]
@kaikreuzer This is the issue I mentioned here https://github.com/eclipse/smarthome/issues/4871#issuecomment-362714353

In the course of analyzing https://github.com/eclipse/smarthome/issues/4871, I noticed an unrelated condition where memory utilization would increase continuously. The condition was caused by entering an invalid binding name in `services/addons.cfg`. Since an error is not logged due to an invalid binding name in addons.cfg, it's possible that a user would not easily be able to determine the cause.

Here's the base memory data collected while I had sar running. 
[openhab-pidstat.txt](https://github.com/openhab/openhab-core/files/1690954/openhab-pidstat.txt)

I used the following command, where `12299` was the pid of the openhab java process.
```
sudo pidstat -r 6 -p 12299
```

Here's a graph of minflt/s and RSS plotted over time. 
- The memory began to increase every minute (presumably when the feature installer runs) as soon as I added an invalid binding name to addons.cfg.
- The memory consumption flattened out as soon as I removed the invalid binding name from addons.cfg 

![sar-minflt-rss](https://user-images.githubusercontent.com/19286354/35756490-953b5c8e-0839-11e8-9a69-f3a8bdff3a9b.jpg)

This was a short duration test to illustrate the issue. I had other tests that ran much longer.

Edit: Note that I was running build 1194.

**Comment by kaikreuzer** [comment]
Thanks, this indeed looks like some memory leak.
It is ok that the feature installer kicks in once a minute - this is actually what it does, it checks whether all add-ons are installed as requested and if not, it tries to do so. But this must clearly not result in any memory issues.

**Comment by abedwardsw** [comment]
I am not 100% sure if this is related, but I was having issues where I was seeing the message “Offline: waiting for connection to become available” quite often after I upgraded to 2.4, I happened to stumble on this issue due to the related thread https://github.com/eclipse/smarthome/issues/4871#issuecomment-362714353

I eventually figured out that I had the mqqtitude binding listed in addons.cfg which was only available in the legacy bindings repo, therefore it didn't auto install after the upgrade.   I removed the binding from addons.cfg and my issues with "Offline: waiting for connection.." in paperui went away.   

I guess at minimum, it would be nice if it logged at the ERROR/WARN/INFO level if it's continuously trying to install the binding.   I later looked at the logs and would only get one error at startup.   I'm guessing this might affect other users during upgrades as well, be nice to at least add more logging if the fix isn't easy to stop the underlying issue causing the offline error message in paperui.

**Comment by mhilbush** [comment]
@kaikreuzer @wborn It looks like the behavior is different (and better) in 3.0. From what I can see, after two failed attempts to install an invalid binding, it no longer tries to install the invalid binding again. Therefore, the process's memory footprint no longer continues to grow over time. 

If my understanding of this is correct, I think this issue can be closed.

**Comment by wborn** [comment]
Yes it no longer retries indefinitely with https://github.com/openhab/openhab-core/pull/1617.

**Comment by kaikreuzer** [comment]
Happy to hear that this is solved with #1617!
