### ISSUE TITLE
jsondb files truncated to zero if volume is full

### ISSUE THREAD

**Issue by brianwarner** [openhab/openhab-core#2989]
I searched for an existing issue and didn't see one, my apologies if this has already been raised.

I'm on 3.0.2 (release build), OpenHABian, Raspberry Pi. Unbeknown to me, I had run out of space on my root volume. I cleared some space, rebooted, and found I had no more Things or Users. Inspecting `$userdata/jsondb`, I found those two JSON files were 0 bytes, as were all of the snapshots in `$userdata/jsondb/backups`. Fortunately, I had a recent offsite backup and was able to restore them pretty easily.

I haven't done deep digging, but my guess is that when the jsondb files are updated, OpenHAB is overwriting the existing file without first checking whether the write will fail due to lack of space on the volume. The filesystem will gladly remove the existing file, but can't write its replacement. If the user doesn't notice and the OpenHAB service exits, the User/Items/Things/etc. states stored in memory are lost and all OpenHAB has upon restarting is an empty file. If it's been a while since a successful backup, then the internal backups will also be empty files and a user will be in a very unfortunate position.

I'm not 100% sure I have my arms around this, but here are a few initial thoughts.

* If a user discovers their volume is full, they can recover by logging in (to recreate the Users file) and wait as long as possible to reboot so the other Thing, Channel, Items, etc. files are recreated. They definitely should not immediately reboot after freeing up space! Maybe we can add this to the "Error writing JsonDB ... No space left on device" log message?
* I see that the log contains an accurate error message. This seems like a pretty urgent error that should be surfaced to the user immediately in all possible ways, as by the time it happens the volume is already corrupted. I'm not familiar with how we handle this, but is there a way to surface this as "extremely urgent problem has occurred" in UIs other than the log? This seems "red banner at the top of every single page"-worthy.
* Is anyone familiar with the way jsondb files are written? I'm not familiar with this part of OpenHAB, but is it possible to write the new JSON as a temp file and test whether that succeeded before removing the existing JSON file?

Thank you!

**Comment by mstormi** [comment]
Since you opened this issue in openhab-core, you're asking core developers to fix some misbehavior in their software.
but in the first place, there isn't any such misbehavior:
if space is full you cannot write to file, neither jsondb nor any temp file nor any other.
Not saying handling cannot be improved, but I believe you will get to see errors in the log assuming you've set your log levels right. There's no other 'superior' mechanism to actively inform users about problems, no matter if major ones.
There's nothing the people you're asking to fix this can do about this in the software.
Unfortunately, it's your very own job as the operator of the computer OH is running on to ensure that space is available.

Analysis of log errors is yours, too. Short of avoiding the trigger (no space) and the whole problem to happen in the first place, there's a myriad of possibilities how to do that.
For example there's the logviewer binding that scans the OH log for specific messages. You can write an OH rule to immediately inform you of occurences through the medium of your choice.

**Comment by J-N-K** [comment]
I disagree - a little bit. You are fully correct that it is impossible to write to a full disk and that can only be fixed by the operator. But: in that case the old jsondb should stay in place, it should not be replaced by a corrupt or empty database because there was no space to write the new version.

**Comment by wborn** [comment]
The backup corruption is already prevented with #2746 in OH 3.3.

**Comment by J-N-K** [comment]
But if I understand it correctly, it‘s not the backup but the current db in this case, is that also covered?
