### ISSUE TITLE
Transformations via map not working

### ISSUE THREAD

**Issue by jzielke84** [openhab/openhab-core#3048]
Map transformation add-in has been installed and the file is parsed (removing an active state value causes the log to throw a "target value not found in map" error) but in the UI it's still the untransformed state. The UI behaves like no state transformation has been set.

/etc/openhab/transform/washer.map:
`INITIAL=Einschaltet`

Log:
`'Waschmaschine_WasherState' changed from NULL to INITIAL`

Pattern in StateDescription:
`MAP(washer.map)=%s`

Result: Still the raw state value, no mapping. If I copy the content from the map file directly into options it works.

**Comment by jzielke84** [comment]
@J-N-K No, its not working. The cell is displaying the english value instead of my mapped translation. When I add those values to the options directly the thing overview also shows the translated value as well as the cell.

**Comment by J-N-K** [comment]
Profiles and state descriptions are different things. The profile changes the value before it gets to the item. The state description takes the item's value and changes it before it gets displayed:

```
incoming value from channel
(optional profile)
item state
(optional state description)
display
```

The state description is not applied in the view you showed, it's only used e.g. in Basic UI sitemaps and in Main UI widgets (i.e. in pages), not in the settings view (that always shows the raw value of the item, which is why it works if you use the profile).

Since the linked issue is an UI issue and if I read the forum thread right already has an issue, I'm closing this one here.

Yes, good eyes :-) Since "Praise the Fallen".

**Comment by jzielke84** [comment]
@J-N-K Thanks for helping me out. In case you'll attend next Amphi or WGT drop me a message on Gitub and I'll offer you a drink for your help in case we meet ;-)
