### ISSUE TITLE
[enhancement] use the persistence service configured in the item (not only the standard service)

### ISSUE THREAD

**Issue by Gifford47** [openhab/openhab-core#3103]
If I do not use the default persistence service for an item, I have to specify the persistence service in rules or diagrams every time I want to retrieve older values.
It would be very handy if OH would select this automatically depending on whether OH finds the item first in the standard persistence service or not.

**Comment by Gifford47** [comment]
But does the PR also handle the automatic selection of the item's persistent service?

**Comment by J-N-K** [comment]
Automatic selection of an arbitrary persistence service is not possible. You can configure different persistence services for the same item. E.g. RRD4J for long-time storage and MapDB for restoreOnStartup. This may make sense because RRD4J is not loss-less, but very good for storing many values where the exact value is not so important (e.g. temperatures).

**Comment by J-N-K** [comment]
I'm closing this as the way it is now is a fundamental design decision.
