### ISSUE TITLE
Enable `<>` as icon in .items files

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-core#3173]
Some elements have a default icon in a sitemap file, like Group, and one way to hide the icon is to amend in the sitemap file `icon=""` after the item.  Amending `icon="none"` also works.

The icon name can be entered also in the .items file in the `<iconname>` format, like
```
Switch r2_manual "Управление[]" <none> {channel="mqtt:topic:r2:r2_manual"}
```
When I use instead `<>`:
```
Switch r2_manual "Управление[]" <> {channel="mqtt:topic:r2:r2_manual"}
```
the parser logs:
> 2022-11-23 15:25:53.614 [WARN ] [el.core.internal.ModelRepositoryImpl] - Configuration model 'r2.items' has errors, therefore ignoring it: [5,50]: no viable alternative at input '>'

Since in .sitemap files can be entered `icon=""`, in `.items`  `<>` should also work equally good.

I am using openHAB 3.3.

**Comment by dilyanpalauzov** [comment]
https://www.openhab.org/docs/configuration/items.html#icons does not say for the icon name, that it must be quoted.  In a `.sitemap` file the icon names must be quoted.  That said, it is possible to enter in an `.items` file as icon `<"">` and `<"temp.png">`, but not `<temp.png>`.  The latter produces the error

> 2022-11-23 15:47:18.701 [WARN ] [el.core.internal.ModelRepositoryImpl] - Configuration model 'r1.items' has errors, therefore ignoring it: [11,61]: mismatched input '.' expecting '>'

I do not see why are quotes necessary in the `<…>` syntax sometimes.  But if quotes are needed, then this shall be documented and some quoted example shall be present.

**Comment by J-N-K** [comment]
I believe this has historical reasons. Originally the part between the brackets was the "category" of the item and that was also used to determine the icon. Since the category is an id and only a limited set of characters is allowed in an id (the dot e.g. is not allowed), you can't just set `<icon.ext>`, because `icon.ext` is not an allowed category. 

A different icon should be set via the `icon` parameter in the sitemap.

**Comment by dilyanpalauzov** [comment]
My findings are that entering `<"temp.png">` in an `.items` file does utilize dynamic icons for Switch and Number items and `<"">` does disable the default icon.  Thus, qoutes do help.  So: it is not documented, when qoutes must be used.

**Comment by lolodomo** [comment]
An item should have a category. If not defined, one default is considered. Using `<>` on the item or `icon=""` in sitemap has no real sense. As you already discovered, the proper way to override the default category/icon is to use for example `<none>` or `icon="none"`.
The ability to use in the items file any string surrounded with double quotes inside `<>` is a syntax error that will be fixed in OH4. You can understand that no UI will properly support something like `<"Let's try with this stupid category/icon !">` even if the syntax in OH3 supports it (by error).
You can follow the discussion with the proposed changes for the icon syntax in #3052.
I suggest to close this issue.
