### ISSUE TITLE
LRUMediaCacheEntryTest unstable

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-core#3507]
This test failed in a Jenkins build: https://ci.openhab.org/job/PR-openHAB-Core/5631

```
[ERROR] Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.524 s <<< FAILURE! - in org.openhab.core.cache.lru.LRUMediaCacheEntryTest
[ERROR] org.openhab.core.cache.lru.LRUMediaCacheEntryTest.loadTwoThreadsAtTheSameTimeFromTheSameSupplierTest  Time elapsed: 0.028 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: array lengths differ, expected: <102400> but was: <0>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertArrayEquals.assertArraysHaveSameLength(AssertArrayEquals.java:428)
	at org.junit.jupiter.api.AssertArrayEquals.assertArrayEquals(AssertArrayEquals.java:205)
	at org.junit.jupiter.api.AssertArrayEquals.assertArrayEquals(AssertArrayEquals.java:63)
	at org.junit.jupiter.api.AssertArrayEquals.assertArrayEquals(AssertArrayEquals.java:59)
	at org.junit.jupiter.api.Assertions.assertArrayEquals(Assertions.java:1226)
	at org.openhab.core.cache.lru.LRUMediaCacheEntryTest.loadTwoThreadsAtTheSameTimeFromTheSameSupplierTest(LRUMediaCacheEntryTest.java:199)
```

It was recently added in #3057 by @dalgwen.

**Comment by dalgwen** [comment]
Probably a concurrency issue, as it is using thread to test multiple access.
I will have a look to make it less error prone asap.

**Comment by dalgwen** [comment]
I ran it literally a hundred times but did not reproduce it.
There should not be a thread issue in this code : the parallel stream collect itself and shoud not have synchronisation issue.

I add some code to get more information from the Exception (it was previously suppressed silently) in [the audio pull request](https://github.com/openhab/openhab-core/pull/3461/files#diff-fc4c620b8884b9070eadbf0036040771d647337733255fb79e871161c3952929) I'm working on.
If (when) it happens again, we could hopefully have the error details.

**Comment by wborn** [comment]
I just had the same test failing in a local build of only the `org.openhab.core` bundle without any additional load on my system.
It might be easier to reproduce if you build the whole bundle or further increase the [fork count](https://github.com/openhab/openhab-core/blob/b745d70d6db9224609acb12192428966f6ef1fc1/bundles/org.openhab.core/pom.xml#L26-L58).

**Comment by wborn** [comment]
Still unstable, see: https://github.com/wborn/openhab-core/actions/runs/5990638947/job/16248161364

**Comment by dalgwen** [comment]
This time I saw a log that I have missed before : 

`[main] WARN  o.o.core.cache.lru.LRUMediaCache - Not enough space for the cache`

So, the cache could't initialize propertly because of a lack of free space. That seems strange because it tried to allocate only 2kb on disk... I must assume that the test runner happens, sometimes, in an environnment with no free space at all. And now I'm not so sure about what to do ?
Should I silently consider the test as a success when the cache is failing, because we are not in good condition and should not assume that the cache implementation is faulty ?

**Comment by wborn** [comment]
I'm using Ubuntu 22.04 with lots of free disk space just like Jenkins (first post).

It also doesn't always fail on macOS.
This build triggered today succeeded: https://github.com/wborn/openhab-core/actions/runs/5997342378

It could also be that it somehow ends up returning no bytes in this path:

https://github.com/openhab/openhab-core/blob/a0eeed9292298b9a44dd752810e7b97e8de0f2e7/bundles/org.openhab.core/src/main/java/org/openhab/core/cache/lru/LRUMediaCacheEntry.java#L309

The result of `FileStore.getUsableSpace()` could also be buggy which has happened before:

https://bugs.openjdk.org/issues/?jql=text%20~%20getUsableSpace

**Comment by dalgwen** [comment]
Sorry, the free space log was a red herring : it is related to the LRUMediaCacheTest on its proper course. (LRUMediaCacheTest ::enoughFreeDiskSpaceTest)

  Finally found the issue. I was able to reproduce it half the time by trying to read the cache entry with 50 concurrent threads instead of 2. I made a PR.

Sorry for letting it slip away so much time.
