### ISSUE TITLE
Default imperial unit for Length changed from inches to feet

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab-core#3552]
The default imperial unit for Length is Inches (see https://www.openhab.org/docs/concepts/units-of-measurement.html), but now it's reporting units in feet.  It has been inches since openHAB 1.

```
2023-04-03 17:57:48.828 [INFO ] [openhab.event.ItemStateUpdatedEvent ] - Item 'nRainHour' updated to 0 ft
2023-04-03 17:57:48.835 [INFO ] [openhab.event.ItemStateUpdatedEvent ] - Item 'nRainToday' updated to 0 ft
2023-04-03 17:57:48.837 [INFO ] [openhab.event.ItemStateUpdatedEvent ] - Item 'nRainWeek' updated to 0 ft
2023-04-03 17:57:48.838 [INFO ] [openhab.event.ItemStateUpdatedEvent ] - Item 'nRainMonth' updated to 0.025590551181102362 ft
```

**Comment by robnielsen** [comment]
It's raining here now.

`2023-04-15 08:31:04.950 [INFO ] [openhab.event.ItemStateUpdatedEvent ] - Item 'nRainHour' updated to 6.561679790026247E-4 ft`

**Comment by J-N-K** [comment]
As I already said: You can set the state description to `%.2f in` and it's fine. 

I see your use-case (and I agree that it is very common to use `"` for inch and `'` for foot), but I also see that `"` is used as alias for seconds and `'` for minutes. This is a problem, because unit labels are global, they are not restricted to the dimension "length" or "time". So we can't infer the dimension from the unit. The question is whether we think that `"` for inch is far more common than for seconds, in that case we could probably implement it.

**Comment by robnielsen** [comment]
It's definitely a regression from prior behavior (pre 4.0), especially when dealing with devices that report values in mm or less.  For example the Netatmo rain gauge has an accuracy of 0.1 mm which is 0.000328084 ft.

**Comment by robnielsen** [comment]
Thinking more about this, I can't think of any use cases that would prefer feet over inches for home automation.

**Comment by spacemanspiff2007** [comment]
@J-N-K 
This issue should be gone with the [new UoM concept](https://github.com/openhab/openhab-core/issues/3282) in 4.0, however this once again shows that implicitly picking a default unit and scale (in this case length) will always lead to confusion.
So I am once again begging you:

Please let's not do
```
Number:Length MyItem
```
which will currently default to 
```
Number:Length MyItem {unit="ft"}
```
but instead make the user pick the normalization like this:
```
Number MyItem {unit="ft"}
```

@robnielsen would have picked the correct unit intuitively in this case:
```
Number MyItem {unit="in"}
```

**Comment by J-N-K** [comment]
The dimension will not be stripped from the item, if we do that, then UoM improvements will not make it into OH4. It requires too many refactoring also in openhab-addons.

**Comment by robnielsen** [comment]
Is there a reason that OH can't use the unit associated with the QuantityType? Netatmo creates a QuantityType with the unit `MILLI(SIUnits.METRE)` for rain measurements. I would suggest that anything less than `SIUnits.METRE` should be represented in inches instead of feet.  Or the simpler solution, just revert back to the way it used to work with inches.

**Comment by robnielsen** [comment]
It snowed yesterday, and its starting to melt:
```
2023-04-17 09:48:43.936 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'nRainHour' changed from 0 ft to 3.2808398950131233E-4 ft
2023-04-17 09:48:43.946 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'nRainToday' changed from 0 ft to 3.2808398950131233E-4 ft
2023-04-17 09:48:43.948 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'nRainWeek' changed from 0 ft to 3.2808398950131233E-4 ft
2023-04-17 09:48:43.959 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'nRainMonth' changed from 0.055446194225721786 ft to 0.0557742782152231 ft
```
This translates to 0.004 in in the Netatmo app.

**Comment by J-N-K** [comment]
@robnielsen The issue with using the attached unit is that we don't know the unit e.g. when restoring data from persistence (because persistence stores only the numeric value, not the unit). 

Did you change the state description as suggested above?

**Comment by robnielsen** [comment]
@J-N-K, yes I could, but the issue is that changing to feet as the default is a breaking change, with no real benefit.

**Comment by kaikreuzer** [comment]
@J-N-K & @rkoshak: If this is indeed a regression, does anything speak against changing the default unit from `ft` to `in`?
I tend to agree with @robnielsen that for home automation, most relevant lengths are be measured in inches.

**Comment by J-N-K** [comment]
I don't care, this should be decided by those who use imperial units :-)

**Comment by kaikreuzer** [comment]
Fully agree, that's why I also tagged @rkoshak. 😄

**Comment by mhilbush** [comment]
I also would vote for inches.

**Comment by robnielsen** [comment]
I use imperial units and vote for inches.

**Comment by rkoshak** [comment]
I don't have a strong opinion any way. Back when @J-N-K asked for my opinion on setting the defaults I thought it would make sense to have the defaults somewhat match the metric defaults. Since meters is the default for length and it makes no sense to choose yards as the imperial default I compromised on feet. As has always been the case, if the default isn't right, it can be overridden through the state description (or hopefully the new UoM approach in OH 4).

Ultimately you'll have someone who isn't happy. For weather you want inches. For the milage on you car you want miles. No default is going to work for everyone.

But I wonder if the default for metric should be considered. Maybe cm makes more sense there?

Ultimately I'm more about consistent than anything.

**Comment by J-N-K** [comment]
If we go back to `m`/`in` we are "consistent" in the sense "it has always been that way".

**Comment by kaikreuzer** [comment]
That's for me the strongest argument here - backward compatibility.

**Comment by J-N-K** [comment]
What about area? It is currently sq. ft., but was not set originally. Shall we change that to sq. in., too?

**Comment by mhilbush** [comment]
> What about area? It is currently sq. ft

Sq ft is the most commonly used unit for area in my experience.
