### ISSUE TITLE
Refine addon.xml `connection`

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-core#3555]
Discussion extracted from openhab/openhab-addons#14813

@J-N-K posted:
> If cloud is used for discovery it's `cloudDiscovery`, if it accesses the cloud (or a remote service) during normal operation, it's `cloud` and otherwise it's `local`.

Sorry if the following can be perceived as pedantic. My intention is only to try to get this right, now that we have this box opened.

The original issue definition by @kaikreuzer (openhab/openhab-core#2058):
- `local` (for add-ons that) interacts locally
- `cloud` if it connects to an online service (seldom or continuously)

The [documented](https://next.openhab.org/docs/developer/addons/addon.html#xml-structure-for-add-on-definitions) definition (highlighting important words) by you (openhab/openhab-docs#1872):
- `local` for add-ons that **only** interact locally
- `cloud` for add-ons that **require** a cloud connection
- `cloudDiscovery` for add-ons that **require** a cloud connection for set-up

And what you just wrote:
- `cloudDiscovery` if cloud is used for discovery
- `cloud` if it accesses the cloud (or a remote service) during **normal operation**
- `local` otherwise (i.e. if it doesn't access the cloud during **normal operation**)

There are slight contradictions here, even between your own definitions. If it doesn't **require** cloud, but **accesses** cloud during **normal operation**, then according to your first definition it's inconclusive - it doesn't **require** cloud, but it also doesn't interact locally **only**. According to your new definition it would be `cloud`, even if it can run perfectly well locally without cloud.

For me as a user, the questions I would expect immediate answers for are:
- Can it run locally without being dependent on an internet connection or any external service?
- Even if it can, will it still call some external services, for example to provide extended functionality?

We cannot clearly answer that with the current options.

I would propose the following (explanations, not descriptions to be used):
- `none` if it runs locally in the openHAB instance without any network dependencies, even local.
- `local` if it runs entirely locally (LAN) and will never call external services.
- `hybrid` is it runs locally, but can optionally also use external (cloud) services for added functionality. This includes what is now called "cloud discovery" which cannot also be seen as "added functionality".
- `cloud` if entirely dependent on external cloud services.

_Originally posted by @jlaur in https://github.com/openhab/openhab-addons/issues/14813#issuecomment-1509734325_

**Comment by wborn** [comment]
For me it was also not clear if this is only about IP connections or also includes connections of other kinds like serial/Bluetooth etc. That distinction also impacts if the connection would be `local` or `none` .

**Comment by J-N-K** [comment]
The `connection` is only for information and my understanding is that the idea was to indicate to the user if he needs internet access for the operation or not. So I would say that 

- `none` is for things like `astro` or `mapdb` and also the transformation and scripting add-ons, because they don't interact with other systems at all. 
- `local` for everything that interacts with "on-site" devices, this would usually cover serial devices (it's not impossible, but at least uncommon to use serial connections from remote systems). IMO this also includes most persistence services, because usually a MySQL or InfluxDB instance will be used that'll work even if openHAB has no access to the internet.
- `cloudDiscovery` is something like the SmartHome/J Tuya Binding: it uses a cloud connection for discovering and configuring devices, but in normal operation it works without internet access.
- `cloud` is e.g. for `mielecloud` or `telegram` where data is acquired from or send to a remote system and the add-on will not work at all if the internet can't be accessed.

Again: since this is only informational, we should select what is most common, even if there are edge-cases that could qualify for another category. Regarding `remoteopenhab`: It depends if it is more commonly used for connecting two openHAB instances (like OH 2/OH3) which are on the same network or if most users would use it for coupling to remote instances over the internet.

**Comment by andrewfg** [comment]
> also not clear if this is only about IP connections or also includes connections of other kinds

Indeed. I am thinking of ZWave usb sticks in particular.

**Comment by jlaur** [comment]
@J-N-K - just to be clear, my suggestion is to abandon `cloudDiscovery` and generalize it to `hybrid` (or something similar). This would still cover the Tuya binding, but also cover cases like Sonos (see https://github.com/openhab/openhab-addons/pull/14776#discussion_r1161582270) where the binding works locally without Internet, but can download album art from the Internet.

It seems we already agree on `none`.

Should we make it clear that `local` is agnostic to the physical connection, so it doesn't matter whether connected by LAN, Wi-Fi, Bluetooth or serial (as examples).

**Comment by J-N-K** [comment]
So:

- `none`: no interaction with external systems at all
- `local`: interaction with external systems, without internet access
- `hybrid`: interaction with external system, internet access required only for discovery and/or additional functionality
- `cloud`: interaction with external systems, internet access required for normal operation

Correct? This can be documented in the XSD similar to this:

```
      <xs:simpleType name="connectionType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="local">
                <xs:annotation>
                    <xs:documentation>Add-on interacts with external systems, but does not require internet access.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="cloud"/>
            <xs:enumeration value="cloudDiscovery"/>
        </xs:restriction>
    </xs:simpleType>
```

**Comment by wborn** [comment]
I think that will work. :+1: 
The hybrid type could also be used for add-ons like remoteopenhab. WDYT @lolodomo?

**Comment by lolodomo** [comment]
Hybrid should then be used for sonos. 

For remoteopenhab, hybrid could be a reasonable compromise, considering that access through openHAB cloud would be only an additional functionality.

**Comment by jlaur** [comment]
I've created a draft pull request with this proposal. If accepted, I will only create one for openhab-docs also.

**Comment by jlaur** [comment]
> If accepted, I will only create one for openhab-docs also.

Here it is: openhab/openhab-docs#2069
