### ISSUE TITLE
Unexpected item state restore with OH4 and out of order events

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab-core#3605]
`OpenHAB version 4.0.0 (Build #3417)`

When creating an item that existed during the runtime before openHAB issues unexpected events.
The item is created through the Api explorer, no other interaction is done with openHAB.
No `*.persistence` file was created and no persistence service is configured:
![grafik](https://github.com/openhab/openhab-core/assets/10754716/05739fe3-75a8-49fb-b0f5-7498848acac6)

Even worse openHAB issues an `ItemStateUpdatedEvent` and an `ItemStateChangedEvent` **_before_** issuing the `ItemAddedEvent`.
See the timestamps of logged SSE events

````
[2023-05-10 16:23:05,170] [  HABApp.EventBus.openhab]    DEBUG | {"topic":"openhab/items/Temperature_event_test/stateupdated","payload":"{\"type\":\"Quantity\",\"value\":\"55.55 Â°C\"}","type":"ItemStateUpdatedEvent"}
[2023-05-10 16:23:05,170] [  HABApp.EventBus.openhab]    DEBUG | {"topic":"openhab/items/Temperature_event_test/statechanged","payload":"{\"type\":\"Quantity\",\"value\":\"55.55 Â°C\",\"oldType\":\"UnDef\",\"oldValue\":\"NULL\"}","type":"ItemStateChangedEvent"}
[2023-05-10 16:23:05,170] [  HABApp.EventBus.openhab]    DEBUG | {"topic":"openhab/items/Temperature_event_test/added","payload":"{\"type\":\"Number:Temperature\",\"name\":\"Temperature_event_test\",\"label\":\"New Item\",\"category\":\"\",\"tags\":[],\"groupNames\":[]}","type":"ItemAddedEvent"}
````

OH3.3 works as expected and does not show this behavior.

**Comment by spacemanspiff2007** [comment]
Reproducible with the latest build
````
OpenHAB version 4.0.0 (Build #3457)
````

**Comment by spacemanspiff2007** [comment]
Still reproducible with ``4.0.0-SNAPSHOT - Build #3476``

**Comment by J-N-K** [comment]
Regarding restoring and event creation: 

The restore is not unexpected. If you install a persistence service and provide no configuration, the default configuration is used. And that is "apply default strategies to all items". In case of rrd4j the default strategies are:

```
    @Override
    public List<PersistenceStrategy> getDefaultStrategies() {
        return List.of(PersistenceStrategy.Globals.RESTORE, PersistenceStrategy.Globals.CHANGE,
                new PersistenceCronStrategy("everyMinute", "0 * * * * ?"));
    }    
```

Regarding event ordering:

Since we run multi-threaded for most event processing, we cannot guarantee correct ordering for events of different types (i.e. all `ItemStateUpdatedEvent`s should retain their order, but `ItemStateUpdatedEvent` and `ItemUpdatedEvent` are created from different places and may have a different order.

In this specific case the reason is that the `ItemChangeListener`s (which receive notifications about added/removed/updated items) are notified by the registry before the respective event is posted. As a result the `PersistenceManager` may set the item state (and thus create the `ItemStateUpdatedEvent`) before all listeners are notified and the `ItemAddedEvent` is posted.

We can fix it here by swapping the notification order (i.e. first send event, then notify listeners), but you could still run into ordering issues in other places.

**Comment by spacemanspiff2007** [comment]
> The restore is not unexpected. If you install a persistence service and provide no configuration, the default configuration is used. And that is "apply default strategies to all items". In case of rrd4j the default strategies are:

I have not installed `rrd4j`. I unpack the openHAB zip, drop the `addons.kar`, start openHAB, enter credentials, skip the assistant and run my tests.

Upon your hint I checked the persistence service and you are correct - `rrd4`j was indeed installed.
Is this something that changed between 3.3 and 4.0 on first startup? (e.g. rrd4j gets installed automatically).
Once I remove rrd4j manually my tests are more or less passing again.



> We can fix it here by swapping the notification order (i.e. first send event, then notify listeners), but you could still run into ordering issues in other places.

No need, now that I know that rrd4j gets installed automatically I can remove it

**Comment by florian-h05** [comment]
> Is this something that changed between 3.3 and 4.0 on first startup? (e.g. rrd4j gets installed automatically).

AFAIK no. RRD4J gets auto installed at least since openHAB 3 because the UI „needs“ persistence for the graphing feature and trendlines (mentioned here https://github.com/openhab/openhab-distro/pull/1455#issuecomment-1368252071).

I recently changed the setup wizard to recommend addons for installation, see https://github.com/openhab/openhab-webui/pull/1821), currently JS Scripting (needed for Blockly) and RRD4J (default persistence) are recommended, but no one removed RRD4J from the default installation afterwards. I will open a PR soon.

**Comment by spacemanspiff2007** [comment]
> AFAIK no. RRD4J gets auto installed at least since openHAB 3 because the UI „needs“ persistence for the graphing feature and trendlines (mentioned here [openhab/openhab-distro#1455 (comment)](https://github.com/openhab/openhab-distro/pull/1455#issuecomment-1368252071)).

It's entirely probable that I removed it and forgot about it - maybe I am getting old 😉 .
Or maybe because I started the installation without internet access and without the `addons.kar`.



> RRD4J (default persistence) are recommended

This is how I would have expected it. A recommendation that is pre selected in the wizzard.

**Comment by florian-h05** [comment]
PR to remove RRD4J from distro is open, see https://github.com/openhab/openhab-distro/pull/1543.

> This is how I would have expected it. A recommendation that is pre selected in the wizzard.

This is also how it is now 👍

**Comment by spacemanspiff2007** [comment]
Thanks!
