### ISSUE TITLE
getThing('someThing').setLabel('aLabel') does not persist after a restart

### ISSUE THREAD

**Issue by proggprod** [openhab/openhab-core#3648]
## Expected Behavior

When a rule or script runs the command
`getThing('someThing').setLabel('aLabel') `
The label of the Thing should change as expected, and when openhab restarts the Thing should still have this new label

## Current Behavior

When openhab is restarted, the label returns to whatever it was set to previously.

## Steps to Reproduce (for Bugs)

1. Choose any Thing in your list or add one.
2. Note the name (Label)
3. Create a new javascript script or rule and run the command 
4. `getThing('UIDOfThing').setLabel('newLabel')`
5. Notice that the thing's label has changed. As expected.
6. Restart openhab
7. The label of the Thing has reverted to the previous label 

## Your Environment

* Version used: (e.g., openHAB and add-on versions)
* Environment name and version (e.g. Chrome 111, Java 17, Node.js 18.15, ...):
* Operating System and version (desktop or mobile, Windows 11, Raspbian Bullseye, ...):

**Comment by J-N-K** [comment]
This is not a bug. Changing things requires updating the thing in the registry, not modifying the thing instance itself.

**Comment by proggprod** [comment]
If it's not a bug how do I make it persist? What would be the point of it not sticking? The docs don't describe this.

**Comment by J-N-K** [comment]
You need to get the thing registry and call "update" with the updated thing as parameter.

**Comment by proggprod** [comment]
Like this???
`getThing('UIDOfThing').update`
I can't find any mention of any of this in the docs

**Comment by clinique** [comment]
You're by passing common usage - reaching dev side

**Comment by proggprod** [comment]
What would be the common usage of renaming a label that  doesn't persist?
I'm pretty sure I'm not mad for thinking that renaming something should persist after a restart.

Could you just tell me how to do this?

**Comment by clinique** [comment]
Let say it differently: you're diving -at the surface - of OH Core guts. Don't expect this to be fully user documented as it is not the intended audience.

**Comment by proggprod** [comment]
Thanks for the help.

But I don't understand the resistance I'm sensing from everyone???
The functionality of renaming a Thing label is stated in the main docs in the first few lines about Things. If it's not for rules or scripts then what is it for?
![image](https://github.com/openhab/openhab-core/assets/81530084/11cfb279-18d6-4eb9-a1a8-6714e22c3c47)
 
The nature of (and beauty of) software is that people will always find a new yet unintended use for something. 
When I bulk import things, I often want to change the default naming for a lot of items at once. So a rule is perfect for this. I don't see what's so strange about this. The reason to do this in a rule is to avoid 100 mouse clicks and typing almost the same thing 20 times.

If not persisting is expected behaviour, it's not mentioned anywhere. And when would not persisting be desirable behaviour?

**Comment by rkoshak** [comment]
> The reason to do this in a rule is to avoid 100 mouse clicks and typing almost the same thing 20 times.

There are other ways to handle that use case including the karaf console, REST API, text based .things files, etc. Rules in general are not really intended to be 

> The functionality of renaming a Thing label is stated in the main docs in the first few lines about Things.

I suspect that they are there for completeness. You can open an issue on openhab-js to change the implementation of those methods so that the changes get preserved in the registry or remove the methods. I'm surprised to even see they exist in the helper library in the first place. It was probably a case of "while I'm here I may as well be complete" and ultimately it wasn't implemented correctly.

> The nature of (and beauty of) software is that people will always find a new yet unintended use for something.

Sure, but that doesn't mean we are obligated to document each and every possible thing that *could* be done in rules, especially for things that are considered outside the scope of what rules are intended to do. And there isn't a complete lack of documentation. It's there in the javadocs and the code, which is where the intended audience for these methods would find them. 

But over all, it's not resistance to what you are doing. It's resistance to the expectation that we would necessarily cover it in the end user docs.

**Comment by florian-h05** [comment]
> You can open an issue on openhab-js to change the implementation of those methods so that the changes get preserved in the registry or remove the methods.

Feel free to open an issue so I have a reminder to fix this once I have the time.

> I'm surprised to even see they exist in the helper library in the first place. It was probably a case of "while I'm here I may as well be complete" and ultimately it wasn't implemented correctly.

I added this in https://github.com/openhab/openhab-js/pull/132, and IIRC it was like you described: If I’m here …
