### ISSUE TITLE
Profile JS Transformation Item ->  Thing for Datatype Datetime not triggered 

### ISSUE THREAD

**Issue by olili** [openhab/openhab-core#3694]
JS-Transformation in a profile for direction item to thing is not triggered in case input value is of datatype datetime. 

Details  see also reference https://community.openhab.org/t/oh4-m4-problem-with-profile-js-transformation-of-datetime-type/147662

OH4 Milstone 4

**Comment by J-N-K** [comment]
Did this ever work (i.e. with the JS transformation in OH3)?

**Comment by J-N-K** [comment]
@kaikreuzer @wborn @cweitkamp 

With the script profile it is more obvious than with the other profiles, but in general the issue exists for a lot of combinations like this (I just picked the above)

- a channel of type `String`
- a profile that converts `String` to `DateTimeType` (and vice versa)
- an item of type `DateTime` 

The `CommunicationManager` sees the `DateTimeType` command from the item and the channel type `String`. The command is discarded, because `String` channels don't accept `DateTimeType` commands (only `StringType` and `RefreshType`). 

Profiles currently have no way of letting the framework know what they can do (and it's not super easy to determine, because a scripting profile may accept and return arbitrary types). Discarding values in the case outlined above (which may also occur for other combinations) seems to be wrong, too.

What would be the best way to handle that?

**Comment by kaikreuzer** [comment]
Sorry for not taking the time to look deep into the code myself, but why exactly is it working for Switch oder Color items, but not for DateTime?

**Comment by J-N-K** [comment]
It doesn't work for most combinations. It depends on the the channel type and the exact command. I have proposed a fix for that. It passes the "raw" command to the profile (except UoM handling) and applies the "toAcceptedType" function on the result of the profile. That seems to be more correct than what we do now. Tests pass with this change (except one that did test exactly the "wrong" behavior, but I replaced that with a test for the later behavior.

There is also a bug in the profile context which was also fixed. 

However, I'm not sure if there are side-effects, I would prefer extensive testing.

**Comment by MisterBJ** [comment]
Hello everyone,

I have also problems with a Shelly Plus2PM (firmware 0.14.1) under OH 4.0.3.
I can't operate this as a switch channel because I become under shellies/shellyplus2pm-1/status/switch:0 an JSON format which contains the status as true/false. That's not the problem (there's JSONPATH for that) but as a command (shellies/shellyplus2pm-1/command/switch:0)
Shelly expects an on/off (only lower case!). So I created a string channel and also selected ECMAScript for the linked switch item in the profile and entered shellySwitch.js.
A log entry should also be made in the script. It does with Thing to Item Transformation but not with Item to Thing Transformation.

I just wanted to note that unfortunately it doesn't work with Switch/String either.

shellySwitch.js
`(function(data) {
  console.info('Entered transformation with "' + data + '"!');
  if (data == 'ON') {
    returnValue = "on";
  }
  if (data == 'OFF') {
    returnValue = "off";
  }
  if (data == 'true') {
    returnValue = 'ON';
  }
  if (data == 'false') {
    returnValue = 'OFF';
  }
  return returnValue
})(input)`


Best regards,
Björn

**Comment by olili** [comment]
problem came back with update to 4,2,1

Profile-transformation "thing" -> "item of type datetime" are not working. 

return code of transformation script is:  return (time.toZDT(String(data).slice(0, 10)))

console.log(time.toZDT(String(data).slice(0, 10))) is correct.

 Any hint?
