### ISSUE TITLE
REST Addon Service Taking 8+ seconds to return

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-core#3959]
I have noticed for awhile that when navigating to the Settings page in the main UI that it hangs for several seconds before loading.  This seems to be due to a REST call to `/rest/addons?serviceId=all` taking  over 8 seconds to return on my system.  I went ahead and spun up a new OH instance with nothing in it, and out of the box its also taking the same amount of time.   Wondering if this can return faster vs having to change the UI code to deal with the long load time (or some other client solution)?

**Comment by J-N-K** [comment]
I believe the reason is that we need to get the information from remote-add-on services (community marketplace, JSON 3rd party). The community marketplace needs to parse a lot of forum posts and is notoriously slow. We already cache the result for (I believe) 15 minutes, so that we don’t need to do that on every call. But this does not solve the slow loading at first call.

**Comment by digitaldan** [comment]
Thanks, that makes sense.  I guess we will need to fix this in the UI then, i'll close this and handle the issue there.
