### ISSUE TITLE
Unit °dH could not be parsed to a known unit  for Item Number:AmountOfSubstance

### ISSUE THREAD

**Issue by syntacrsc** [openhab/openhab-core#4307]
When configuring an item of type Number:AmountOfSubstance and specifying to use unit °dH (by adding unit="°dH" in channel-linkage) openHab keeps using unit "mol" and issues a warning message to the log such as:

`2024-07-08 11:28:33.129 [WARN ] [penhab.core.library.items.NumberItem] - **Unit '°dH' could not be parsed to a known unit. Keeping old unit 'mol' for item** 'gruenbeckRawWater'.`

Also See:
[https://community.openhab.org/t/problem-with-unit-dh-for-item-of-type-number-amountofsubstance-using-mol-instead-of-dh/157079](url)

## Expected Behavior
The system should use the specified unit °dH as per current documentation in chapter “SI (base unit symbols)”
of [https://www.openhab.org/docs/concepts/units-of-measurement.html](url)

## Current Behavior
openHab issues a warning message and keeps using the default(?) unit mol

## Possible Solution
no clue since I'm by far to novice of a developer to say ;-)

## Steps to Reproduce (for Bugs)
setup an item such as:
`Number:AmountOfSubstance     gruenbeckRawWater            "Wasserhärte Rohwasser [%.2f %unit%]"                                                        {channel="mqtt:topic:MQTTMosquittoBridge:gruenbeckSoftliqSd21:rawWater", unit="°dH"}`
and link it to any channel providing a pure number value

## Context
Encountered the issue while creating a widget for my water softener 
for context details: see [https://community.openhab.org/t/gruenbeck-water-softener-widget/157104](url)

## Your Environment
openHab 4.2.0 release build
Raspberry pi 5b 8GB
Debian GNU/Linux 12 (bookworm)
OpenJDK 64-Bit Server VM (build 17.0.11+9-Debian-1deb12u1, mixed mode

**Comment by jlaur** [comment]
I think there is a bug here:
https://github.com/openhab/openhab-core/blob/918b4faa3b3254a993774147f798e8bc59580bf6/bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/Units.java#L94-L95

the type-cast looks suspicious and I think this is part of the explanation. You _cannot_ convert **mol** to **°dH**, but you _can_ convert **mol/l** to **°dH**. I think the problem is that mole is a unit for the amount of substance:
https://github.com/openhab/openhab-core/blob/918b4faa3b3254a993774147f798e8bc59580bf6/bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/Units.java#L91

but moles per liter is a unit of concentration, indicating the number of moles of substance per liter of solution. So the type-cast is forcing `DEUTSCHE_HAERTE` into a wrong dimension.

I don't think we currently have a dimension for concentration, but this could be added.

@J-N-K might have some more insights/domain knowledge, I have really just been googling this topic without any prior knowledge, so might be complete nonsense. 😉

**Comment by jlaur** [comment]
I also found this: https://www.snowate.com/knowledge-calculator/knowledge/water-hardness-introduction.html

**Comment by J-N-K** [comment]
So it should be dimensionless (like ppm).
