### ISSUE TITLE
Profile transformation "thing" to "item of datetime type" is not working

### ISSUE THREAD

**Issue by olili** [openhab/openhab-core#4366]
problem came with update to 4,2,1

Profile-transformation "thing" -> "item of type datetime" are not working.

return code of transformation script is: return(time.toZDT(String(data).slice(0, 10)))

console.log(time.toZDT(String(data).slice(0, 10))) is correct and showing the right date as string in log file

Any hint?

**Comment by J-N-K** [comment]
Maybe let us know what scripting language you use and what exactly the content of `data` is. That makes it easier to reproduce.

**Comment by olili** [comment]
okay. Following setup to reproduce.
Create a JS-Profle like this.:
`
(function(data) {
  var tmp = time.toZDT('2024-04-15'); 
  console.log( tmp );
  return tmp;
})(input)
`
Link the Profile with a item of type datetime and with any thing that is triggered frequently. 

Result: In my setup the item is not updated. Log output is shown.

Problem came up with update on OH4.2.1. 
Version before no problem.

**Comment by J-N-K** [comment]
The problem is that the return value of your script is an object:

<img width="370" alt="image" src="https://github.com/user-attachments/assets/dd3b14dd-6d5e-44d6-80d7-ed1f72edc680">

The script profile calls `.toString()` on that and that results in a string `[object Object]`. This can't be parsed to `DateTime`.

If that worked in the past, then something within the JS scripting add-on changed. The return value of a script needs to be a string itself or hast to be converted to a meaningful value when calling `.toString`.

So you can modify your script to return a string:

```
(function(data) { var tmp = time.toZDT('2024-04-15');  console.log( tmp ); return tmp.toString(); })(input)
```

Unfortunately this still doesn't work, because `2024-04-15T00:00+02:00[SYSTEM]` is not something that is an allowed format either. If you use the correct formatter

```
(function(data) { var tmp = time.toZDT('2024-04-15');  console.log( tmp ); return tmp.format(time.DateTimeFormatter.ISO_INSTANT); })(input)
```

everything works as expected.

**Comment by olili** [comment]
THX and respect for your competence! O.

**Comment by J-N-K** [comment]
@florian-h05 It seems a bit strange that a `ZonedDateTime` is returned as `PolyglotMap`. Is that intended?

**Comment by florian-h05** [comment]
Wrt to JS Scripting nothing has changed for 4.2.1 IIRC.

The ZonedDateTime is returned as PolyglotMap because it is no Java ZDT but a JS-Joda ZDT and PolyglotMap is GraalJS default approach for handling JS types passed to Java.
The problem here is, that the target type mapping defined in the add-on code does not work, because the expected return type is too generic (without looking at the code, I think Object is expected).
