### ISSUE TITLE
Sitemap Sorting

### ISSUE THREAD

**Issue by mike-petersen** [openhab/openhab-core#449]
It would be nice if the sitemaps could be sorted, e.g. using a order value

This is already discussed for Android and Ios apps (https://community.openhab.org/t/order-of-sitemaps/23693/10, https://github.com/openhab/openhab-ios/issues/166)

(The advantage of an extra sort value would be that you do not have to rename your views or files in order to sort them.)

**Comment by J-N-K** [comment]
After reading the attached thread I do not understand what the issue is. Is it that automatically added items in the sitemap (because you only reference a group instead of an individual item) follow no order or is it that different sitemaps (i.e. different `.sitemap` files) do not show up in a specified order in the sitemap selection of the apps?

**Comment by lolodomo** [comment]
This is apparently related to sitemaps ordering. 
PS: For groups, an ordering setting already exists.

**Comment by J-N-K** [comment]
But how many sitemaps do you have that you require ordering?

**Comment by lolodomo** [comment]
> But how many sitemaps do you have that you require ordering?

lol
Only one for me.
