### ISSUE TITLE
p2 artifact injects repositories

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab-core#501]
@kaikreuzer While inspecting my build log I wonder why there are lookups on the JFrog snapshot repository.
I identified that the p2 artifact adds additional repositories.

What's the use case?

**Comment by kaikreuzer** [comment]
We have this in the parent pom for all openHAB (now [here](https://github.com/openhab/openhab-core/blob/master/features/p2/poms/pom.xml#L74-L99)).

These are virtual snapshot/release repos at our own Artifactory server - the good thing about that is that we are free to change the external repos from where artifacts are retrieved (we e.g. once moved stuff from Bintray to somewhere else, which broke older builds, because artifacts were not found anymore). It therefore serves as a facade for all repos that are not Maven Central.

I'd actually suggest to keep it this way also for the new build.

**Comment by maggu2810** [comment]
You could replace the repositories of the parent POM with a facade, but please stop using snapshot repositories and external snapshot dependencies in the framework itself.
For the addons it needs to be done to refer to the framework snapshots, but consumers of the framework should be able to build custom states without resolving all dependent snapshots.
