### ISSUE TITLE
Handle hexadecimal firmware versions

### ISSUE THREAD

**Issue by YordanDZhelev** [openhab/openhab-core#561]
Currently it is not possible to have hexadecimal string as thing firmware versions. Even though the version is an integer, it cannot be handled correctly by the [isInt(String s)](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/firmware/FirmwareImpl.java#L315) check. It will be either considered not an integer if the version string contains one of `A, B, C, D, E or F` or will be falsely parsed as an integer, but with incorrect value. Such hex versions are already in use in [zigbee binding](https://github.com/openhab/org.openhab.binding.zigbee/blob/master/org.openhab.binding.zigbee/src/main/java/org/openhab/binding/zigbee/discovery/ZigBeeNodePropertyDiscoverer.java#L188). 
I would suggest to change [version comparison](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/firmware/FirmwareImpl.java#L275) to be able to work also with hexadecimal versions by relying on a `0x` prefix infront of the actual version string. 
Such change is already prepared for the zigbee binding in this [zigbee binding PR](https://github.com/openhab/org.openhab.binding.zigbee/pull/384)

**Comment by maggu2810** [comment]
Hi @YordanDZhelev,
what has been the reason to use hexadecimal representation of the firmware version in the ZigBee binding?
Is there any advantage?

**Comment by hsudbrock** [comment]
Maybe @cdjackson knows an answer to @maggu2810 's question above; Chris, do you maybe recall whether there was a particular reason to use hex numbers to represent the FW versions in the ZigBee binding?

**Comment by cdjackson** [comment]
I believe it was done like this to make the versions more readable - as decimal, they mean nothing - but as hex they are usable since mostly each byte is an independent part of the version.

I'm a little surprised that this doesn't work as it has been working ok like this for well over a year. Maybe we got lucky and versions don't contain A-F values.

**Comment by hsudbrock** [comment]
Thanks for your feedback, Chris!

> I'm a little surprised that this doesn't work as it has been working ok like this for well over a year. Maybe we got lucky and versions don't contain A-F values.

I think that @YordanDZhelev's PRs are not actually needed to make "firmware version comparison with hex numbers" work - it already works today, at least if the firmware version is padded with `0`s to a fixed length, as is the case for the ZigBee binding. Why does it work ok without the PRs? Because if one of two compared firmware versions contains A-F values, then the version comparison falls back to comparing the versions as Strings, lexicographically. Due to the padding, this should yield the same result as comparing the parsed hex values.

I, personally, think that it could be helpful to change things nevertheless (either by permitting `0x`-prefixed version numbers as suggested by @YordanDZhelev , or by using decimal numbers in the ZigBee binding), because I find it "too surprising" that it currently works ('just' because the ZigBee binding pads versions, and because for those padded numbers is does not matter whether they are compared as integers, or as Strings). But this might be personal preference...

**Comment by J-N-K** [comment]
Closing this issue as the original requestor didn't want the feature merged (see attached PR).
