### ISSUE TITLE
Gson library version

### ISSUE THREAD

**Issue by paulianttila** [openhab/openhab-core#608]
Used gson library v2.3.1 is pretty old. Can we bump it to latest which is v2.8.5?

I need at least v2.4 to be able to provide binary to json converter openhab/openhab2-addons#4979

API change review: https://abi-laboratory.pro/index.php?view=timeline&lang=java&l=gson

**Comment by maggu2810** [comment]
At which place you would like to bump the Gson version.

The openhab-runtime-base feature provides 2.8.2 at runtime.

```
  <feature name="openhab-runtime-base" description="openHAB Runtime Base" version="${project.version}">
    <bundle>mvn:p2.osgi.bundle/com.google.gson/2.8.2.v20180104-1110</bundle>
```

openHAB Core uses v2.3.1 at compile time for their bundles.
But I don't see any reason to bump that version just because an addon needs a newer one -- it should be enough to use a newer one while compiling the addon.
The requirements at runtime for OSGi bundles are part of the manifest.

I assume you would like to request a bump of the Gson that is provided by the target platform because you use that bundles as compile time dependencies.

The target platform is (AFAIK) provided by https://github.com/openhab/openhab-deps-repo

**Comment by maggu2810** [comment]
Sorry, didn't have a look at the PR itself and its comments.

So, you would like to migrate a bundle to core and the Gson version used in openHAB Core does not fulfill the requirements of your code.

Can you please check the minimum version that suffers your needs you need.

If we bump the compile time dependency used in the core (the file bom/compile/pom.xml) this will result into a new minimum version required by the bundle.

If a product currently uses e.g. 2.7.0 it will not work if we bump the minimum version from 2.3.1 to 2.7.1 or 2.8.5.

The minimum version should be set to the real minimum and not just to the newest one available.

I am personally fine with using a more recent version but we should choose the minimum version responsibly.

* Which function do you need to use?
* Is there an equivalent function in 2.3.1?
* Which version of Gson started to add this function?

**Comment by paulianttila** [comment]
I think I found a way to be Gson 2.3.1 compatible
