### ISSUE TITLE
[Rules DSL] StringUtils Missing since at least 1536

### ISSUE THREAD

**Issue by semperor** [openhab/openhab-core#613]
Hello.
As mentioned in this thread https://community.openhab.org/t/2-5-0-snapshot-build-1536-problems-with-string-methods/68799 the StringUtils methods are not longer available for strings. This started at least with build 1536 and exists in the build 1541.

**Comment by lolodomo** [comment]
I use "replaceChars" in some of my DSL rules and I can confirm that it is no more working:
```
2019-03-03 10:20:32.391 [ERROR] [ntime.internal.engine.RuleEngineImpl] - Rule 'Controle par la voix': 'replaceChars' is not a member of 'java.lang.String'; line 769, column 24, length 45
```
I am running snapshot 1544.

**Comment by lolodomo** [comment]
@kaikreuzer : I still have the issue using replaceChars with snapshot 1549. Is it expected ?

**Comment by semperor** [comment]
Unfortunately still not fixed at all:

https://community.openhab.org/t/2-5-0-snapshot-build-1536-problems-with-string-methods/68799/12?u=semperor

**Comment by lolodomo** [comment]
Can you reopen the issue ?

**Comment by semperor** [comment]
> Can you reopen the issue ?

Unfortunately not, as it was closed by a repo collaborator. @maggu2810 or @kaikreuzer please reopen this issue. Thank you.

**Comment by kaikreuzer** [comment]
Reopened it.
@maggu2810 Any idea why my fix didn't solve it? What else could have changed in the bundle by the bnd migration?

**Comment by maggu2810** [comment]
@kaikreuzer I try to understand, how the packages for explicit imports has been choosen on #620?
As it seems no to solve this specific problem, are this additional packages the ones that needs to be present for scripts and rules?
Which package contains the missing class?
Can someone share a minimal example to reproduce the problem using openHAB Core only?

**Comment by maggu2810** [comment]
@semperor It has been closed because a PR has been merged that contains a "fixes #613". This will trigger Github to close the related issue automatically.

@kaikreuzer I try to understand, how the packages for explicit imports has been choosen on #620?
As it seems no to solve this specific problem, are this additional packages the ones that needs to be present for scripts and rules?
Which package contains the missing class?
Can someone share a minimal example to reproduce the problem using openHAB Core only?

**Comment by openhab-5iver** [comment]
> Can someone share a minimal example to reproduce the problem using openHAB Core only?

@maggu2810, you could test with this DSL rule...

```
rule "Test"
when
    Time cron "0/10 * * * * ?"
then
    val testString = "This test has passed"
    logInfo("Rules", "Test: [{}]", testString.substringAfter("This test has "))
end
```

**Comment by maggu2810** [comment]
I added this DSL rule to my runtime and that's the output of the console:

```text
17:20:02.112 [le-processing-6] INFO  o.e.s.m.c.i.ModelRepositoryImpl:115 - Loading model 'test.rules'
17:20:10.029 [eduler_Worker-1] INFO  o.e.smarthome.model.script.Rules:53 - Test: [passed]
17:20:20.005 [eduler_Worker-2] INFO  o.e.smarthome.model.script.Rules:53 - Test: [passed]
17:20:30.003 [eduler_Worker-3] INFO  o.e.smarthome.model.script.Rules:53 - Test: [passed]
17:20:40.004 [eduler_Worker-4] INFO  o.e.smarthome.model.script.Rules:53 - Test: [passed]
17:20:50.002 [eduler_Worker-5] INFO  o.e.smarthome.model.script.Rules:53 - Test: [passed]
```

**Comment by openhab-5iver** [comment]
This is what I get in S1549...
```
2019-03-07 06:53:10.009 [ERROR] [org.eclipse.smarthome.model.rule.runtime.internal.engine.ExecuteRuleJob] - Error during the execution of rule 'Test': 'substringAfter' is not a member of 'java.lang.String'; line 6, column 36, length 43
2019-03-07 06:53:20.008 [ERROR] [org.eclipse.smarthome.model.rule.runtime.internal.engine.ExecuteRuleJob] - Error during the execution of rule 'Test': 'substringAfter' is not a member of 'java.lang.String'; line 6, column 36, length 43
2019-03-07 06:53:30.004 [ERROR] [org.eclipse.smarthome.model.rule.runtime.internal.engine.ExecuteRuleJob] - Error during the execution of rule 'Test': 'substringAfter' is not a member of 'java.lang.String'; line 6, column 36, length 43
2019-03-07 06:53:40.002 [ERROR] [org.eclipse.smarthome.model.rule.runtime.internal.engine.ExecuteRuleJob] - Error during the execution of rule 'Test': 'substringAfter' is not a member of 'java.lang.String'; line 6, column 36, length 43
2019-03-07 06:53:50.006 [ERROR] [org.eclipse.smarthome.model.rule.runtime.internal.engine.ExecuteRuleJob] - Error during the execution of rule 'Test': 'substringAfter' is not a member of 'java.lang.String'; line 6, column 36, length 43
```

**Comment by maggu2810** [comment]
Sorry, but I don't know about that numbers. I build the master with additional **unrelated** changes myself.

**Comment by kaikreuzer** [comment]
> @kaikreuzer I try to understand, how the packages for explicit imports has been choosen on #620?

I was checking the differences between what is automatically imported by model.script, because [it is used in the code](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.model.script/src/org/eclipse/smarthome/model/script/scoping/ScriptImplicitlyImportedTypes.java#L78) (this line makes the `substringAfter` available in scripts) and added those required imports to the rules, where I assumed it is NOT automatically added as an import, because the `model.rule` bundle does not refer to those classes in its own source code.

My assumption was that this is the very same fix as you did in https://github.com/openhab/openhab-core/pull/572, so I am not really clear why it isn't working :-( .

**Comment by semperor** [comment]
No more errors openHAB 2.5.0~S1555-1 (Build #1555).
