### ISSUE TITLE
[openhab.boot] Split

### ISSUE THREAD

**Issue by davidgraeff** [openhab/openhab-core#660]
Hm. I keep finding sitemap stuff.

The `openhab.boot` package serves multiple different purposes. I propose to

* move "IconForwarder" to combat1x (it proxies /images to /icons for OH1 rest consumers).
* move "DefaultSitemapProvider" to the "ui.sitemap" bundle
* Rename "CoreActivator" to "ModelRuleEngineStart" and move it to "org.openhab.core.model.rule.runtime"
* Move "OpenHab.java" to "org.openhab.core.config". The class provides the static method `getVersion`.
Unfortunately it cannot be moved to " org.openhab.core", because it requires config.core classes to determine the user directory.

Additionally I like to add a REST endpoint "about" that allows to request the openhab version from that mentioned class. A UI cannot request any versions at the moment. Fascinating somehow.

**Comment by davidgraeff** [comment]
@openhab/core-maintainers BUMP

**Comment by maggu2810** [comment]
IMHO

* `OpenHAB`
  Methods like `getBuildVersion()`, `getVersion()` and similar should be provided by a service and this one should be used instead of static functions.
  I would also prefer if first an optional configuration provided by config admin is used and if there is no one, a fallback (e.g. the current code) is used. This allows others solutions to provide overwrite the version by a configuration.

> * Rename "CoreActivator" to "ModelRuleEngineStart" and move it to "org.openhab.core.model.rule.runtime"

okay for me

> move "IconForwarder" to combat1x (it proxies /images to /icons for OH1 rest consumers).

combat1x => compat1x
But could make sense as the redirect from old to new needs only be used if we want to provide a compatibility.

> * move "DefaultSitemapProvider" to the "ui.sitemap" bundle

makes sense

**Comment by davidgraeff** [comment]
A service makes sense as yes
