### ISSUE TITLE
SSE implementation (Jersey vs. Jetty)

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab-core#743]
While having a look at the servlet base classes that are provided by Jetty I stumbled over the [EventSourceServlet](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-servlets/src/main/java/org/eclipse/jetty/servlets/EventSourceServlet.java)

As Jetty is already a hard dependency for openHAB I wonder if it would make sense to use that SSE implementation.

Has anyone used this before and can share their experiences with us?

**Comment by kaikreuzer** [comment]
Afair, this wasn't an option for ESH due to sticking to an older servlet spec - so no, I have no experiences with it.
Now that we don't have a constraint wrt to the servlet spec anymore, it might be a good option to look at (although I do not see the necessity for the effort right now as our current implementation seems to work quite well and changing it is always risky...).

**Comment by wborn** [comment]
Some add-ons may also use Jersey. E.g. the Nest Binding uses the Jersey EventSource client for which there was no Jetty implementation when I implemented the Nest streaming REST protocol.

**Comment by davidgraeff** [comment]
Actually it does not work well. Paper UI as well as my paper-ui replacement design study both suffer from connection drops about every few minutes. And I don't mean regular http long poll session endings. The browser client API just reconnects immediately so the user doesn't notice it.

In #739 I'm updating jersey to the very newest version so that problem might be fixed then.

**Comment by maggu2810** [comment]
> Actually it does not work well.

What does not work exactly? Did you try to replace jersey by Jetty's EventSourceServlet and this does not work?
I suppose you mean something else, as you have written the problem is solved by the Jersey update.

**Comment by davidgraeff** [comment]
I have added the missing quote to my comment to add the context.

**Comment by maggu2810** [comment]
I assume there is no Jersey used anymore.
