### ISSUE TITLE
[Discussion] Auto linking

### ISSUE THREAD

**Issue by davidgraeff** [openhab/openhab-core#749]
The current situation is that in the community people recommend to turn auto-linking off.
The feature is indeed not very helpful, because created items are not fully editable.

I suggest a few points to make this feature usable and hopefully the community does not need to recommend to turn it off in the future.

1. More control for binding developers: Let channel types be annotated with a new property `<autolink>false/true</autolink>`. 
1. Created items should also have better default names consisting of the Thing name + Channel name. We don't need hundreds of "Brightness" items, it is so much more helpful to have "Kitchen Light Brightness" etc. Allow binding developers to influence the default with a new channel type property: `<autolinkname>%Thingname% %Channelname%</autolinkname>`
1. Items are ONLY created if the user agreed and only on Thing creation. So that means while you approve an Inbox Thing, you must pass the parameter "autolink" (default=false?). When you create a Thing manually, you must pass the "autolink" (default=false?) parameter. Can be a yes/no modal dialog in a user-interface.
1. Items are fully standalone / editable. The autolink feature should not interfere with already existing Things or Items. (Instead we would have a separate service LinkThatThing that can be instructed via REST etc to create links for existing Things)

**Comment by kaikreuzer** [comment]
My personal recommendation is also to not use the auto-linking as this is nice for demos to have something to show quickly, but not helpful in real life.
The fact that items appear that are nowhere declared can be very confusing for people.
What imho makes more sense is to have a simple way to create items+links for a given thing easily - like the VS Code extension is already providing it for the textual configuration.
Not sure, if your suggestion is heading the same direction, but it might.

1. So far, the auto-linking is a general concept and not dependent on specific bindings/things/channels. I do not really see a good reason why this should change - I rather fear that it can lead to even more confusion about what is happening.
2. You mean the Thing label + Channel label instead of the UIDs? Yes, this is what Paper UI is already creating as item names in the non-autolinking mode - but technically, we cannot ensure that those are unique, that's why the auto-linking is currently using the UIDs.
3. This still leaves the complexity in place and the novice user in the situation that he does not know what to choose. I'd really love to come to some solution to overcome this, although I do not have a good proposal...
4. What we also have to consider is how you remove such stuff again. Note that the "simple mode" technically only creates links and the items are automagically appearing, if such dangling links exist. Removing the link will also automatically make the item disappear. If you create "standalone" items, you have to create links AND items and both need to be removed, if the item is no longer desired.

**Comment by davidgraeff** [comment]
>  a simple way to create items+links for a given thing easily

Yes that is what I'm aiming for. We might as well come to the conclusion that this feature cannot be "repaired" and that we instead want to focus on easier ways to "mass-link" new and existing Thing channels to items when the user requested it.

> What we also have to consider is how you remove such stuff again.

That's why I want to include the users opinion. In my concept there is no going back / undo if the user deliberately clicked on "Create Items for me". Items and Item links are created in the same way as if the user would have done it with no way to distinguish automatically and manually created items.

I expect a user to know about Thing / Channel / Item concepts at this point in time, but a short description was intended in my original post. But after reading your comment, I'm not entirely sure if auto-linking makes sense at all.

**Comment by JeJeff** [comment]
FWIW, are you willing to take input from a brand new user?

I picked up OpenHAB about a week ago for the first time, and it has been quite a journey already.  Understanding the difference between items and channels, and linking them together has probably been the hardest thing to get my head around.  

I started using 'simple mode' and automatically created items.  I really liked this way of managing things, and with automatic discovery of my things, and automatic items I had very little to do before getting a 'working' system.  But then I hit problems:
- I can't edit these items to add them to groups.
- The naming was arcane.
- I can't see the details of the items (specifically the name) in order to add them to a sitemap.

Next I disabled simple mode and started creating items through Paper UI.  This was pretty great, a bit annoying that I had to click a few more buttons but I still didn't have to type much of anything.  The default items names were much nicer than the automatic ones from simple mode.  I understand in theory you could get a name collision but I didn't encounter this, and it could easily be managed with some validation, or by including a unique ID suffix or something.  But then I hit a few more problems:
- With one particular binding I couldn't link an item to one of the channels because no profiles are available for it.
- I can't set the tags needed to make items work to Alexa, etc.

So now I'm undoing everything I already did and recreating them in files.  I hate this.  It is tedious and error prone.  Formatting the files them nicely is a pain, but if you don't the files become difficult to read.  File based configuration is a massive barrier to entry.

What would I like?
1.  I'd just love the automatic creation of items to work properly, but automatic items _must_ be fully editable in all aspects or there is no point.
2.  With how I'm using OpenHAB so far I'd like to go a step further than 'simple mode' and have the system auto-create an item for every channel as soon as the thing is created.  When I create a thing, or accept an auto-discovered thing from the inbox, I should be able to set my own name and location for it, and have auto created items named using these values.  I want one item for every channel so that they are available for me to use in Node RED and sitemaps, and I've seen no downside in having items in the system that are not being used.
3.  I should be able to see the item configuration section even with simple mode turned on.  I need to know item names if I'm to configure a sitemap.
4.  If I remove a link from a channel the system should ask if I want to delete the associated item or not (or should tell me where the item is configured if it is unable to delete it).

**Comment by openhab-5iver** [comment]
I would like the functionality in a Thing's properties to be able to select an option to create Items for each Channel. And also to remove all Items linked to the Channels. This would be VERY helpful for certain bindings, like OpenWeatherMap, DarkSky, WeatherCompany, etc., where there are ~700 Channels each. The ability to add a Group or Tag would be a really nice feature too.

I have created a Jython script that has this functionality, but it makes sense to me for it to be in a UI.
