### ISSUE TITLE
Circular dependencies

### ISSUE THREAD

**Issue by afuechsel** [openhab/openhab-core#758]
Since the introduction of `CommandDescriptionService` and `StateDescriptionService` two circular dependencies have been created: 

* `ItemRegistry -->  CommandDescriptionService --> CommandDescriptionProvider --> ItemChannelLinkRegistry --> ItemRegistry` 
*  `ItemRegistry --> StateDescriptionService --> ChannelStateDescriptionProvider --> ItemChannelLinkRegistry --> ItemRegistry` 

We should get rid of these.

**Comment by cweitkamp** [comment]
I am trying to figure out if this is a real problem because we have an optional cardinality which AFAIK breaks the cycle. Submitted #987 and #988 for simplification of component lifecycle. 

Quoted from [OSGi Compendium Release 7](https://osgi.org/specification/osgi.cmpn/7.0.0/service.component.html#service.component-circular.references):

> However, if one of the references in the cycle has optional cardinality SCR must break the cycle. The reference with the optional cardinality can be satisfied and bound to zero target services. Therefore the cycle is broken and the other references may be satisfied. 

`ItemRegistry` (`ItemRegistryImpl`) -->
(optional, dynamic) `StateDescriptionService` (`StateDescriptionServiceImpl`) -->
(multiple, dynamic) `StateDescriptionProvider` --> Deprecated


`ItemRegistry` (`ItemRegistryImpl`) -->
(optional, dynamic) `StateDescriptionService` (`StateDescriptionServiceImpl`) -->
(multiple, dynamic) `StateDescriptionFragmentProvider` (`ChannelStateDescriptionProvider`) -->
(1..1) `ItemChannelLinkRegistry` -->
(1..1) `ItemRegistry`


`ItemRegistry` (`ItemRegistryImpl`) -->
(optional, dynamic) `CommandDescriptionService` (`CommandDescriptionServiceImpl`) -->
(multiple, dynamic) `CommandDescriptionProvider` (`ChannelCommandDescriptionProvider`) -->
(1..1) `ItemChannelLinkRegistry` -->
(1..1) `ItemRegistry`

**Comment by cweitkamp** [comment]
Closing this issue now. If we face any problems to the related topic in the future we can open it again.
