### ISSUE TITLE
Introduce core framework metrics

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-core#774]
Follow up of [this discussion](https://github.com/openhab/openhab-core/pull/744#issuecomment-487681836).

We should make use of Eclipse MicroProfile metrics API and provide all kinds of core metrics from openHAB this way - like CPU usage, heap size, number of threads, job queue sizes, event throughput, etc.

Once such information is provided through the API, we can use it to e.g. provide a Prometheus publisher, to provide it through JMX or directly integrate it into the systeminfo binding.

**Comment by kaikreuzer** [comment]
@pokerazor How much effort would it be to port your implementation to the Eclipse MicroProfile API? I only mean the provider side, not the consuming part.

**Comment by pokerazor** [comment]
Hm. Very hard to say for me, as I don't have experience with the Eclipse MicroProfile API ... how could we approach this? What is the aim? What is the downside of using what is currently implemented in the bundle?

**Comment by pravussum** [comment]
Following up on the discussion in #2065 here:
> > Prometheus exporter binding
> 
> Please note that it must not be done as a binding, though. Exposing openHAB for Prometheus probably best qualifies as an I/O add-on. Please also note #774, which would be the preferred way of implementation (i.e. by using the MicroProfile API).

My approach is to write the metrics to items in order to let the user choose how to proceed with them.
* either Prometheus can directly access them via the items state REST API endpoint
* or it can be further processed / transformed / whatever

Why do you write "must not"? What's the downside?

I'll try to push my WIP version tonight.

**Comment by pravussum** [comment]
@kaikreuzer What do you think about using [Micrometer](https://micrometer.io) instead of MicroProfile Metrics? 
MP Metrics themselves plan to [move towards that direction](https://github.com/eclipse/microprofile-metrics/blob/master/spec/src/main/asciidoc/intro.adoc) (implying future effort to migrate it, when going from MP Metrics 3 to 4) and looking at Quarkus, Micronaut and Spring Boot that seems the way to go for me.
https://quarkus.io/blog/micrometer-metrics/

**Comment by kaikreuzer** [comment]
@pravussum Sounds like a very good point. The situation has changed since the initial discussion a few years back and Micrometer seems indeed being the preferred API for all the frameworks out there - so yes, heading for Micrometer sounds perfectly reasonable!

**Comment by kaikreuzer** [comment]
Implemented with https://github.com/openhab/openhab-core/pull/2133.
