### ISSUE TITLE
/rest/items shows "icon" as "category"

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-core#786]
According to the docs I can specify an icon in the items file:

> Group groupname ["labeltext"] [\<iconname\>] [(group1, group2, ...)]

I didn't see the icon in the output of /rest/items, so I had a closer look and saw, that the icon is displayed as "category". Is this intended or a bug?

link | "http://openhab:8080/rest/items/Light_FF_Daughter_Ceiling"
-- | --
state | "NULL"
editable | false
type | "Switch"
name | "Light_FF_Daughter_Ceiling"
label | "Ceiling"
category | "sun"
tags | []
groupNames |  
0 | "FF_Daughter"
1 | "Lights"

**Comment by kaikreuzer** [comment]
That's intended. Actually, the documentation is wrong, because what you specify is a category.
Unfortunately, currently the primary use of this category is to provide icons, so it is often used synonymously. But technically, the icon is merely a visual representation of the category, while the category holds some semantical information as well.

**Comment by mueller-ma** [comment]
Ok, so I can use the category field to fetch the item? In this specific case (https://github.com/openhab/openhab-android/issues/257#issuecomment-269132020) I need to fetch the items directly and not the widgets.

**Comment by kaikreuzer** [comment]
> so I can use the category field to fetch the item?

If you mean "icon" instead of "item": Yes!
