### ISSUE TITLE
Cron job execution stops after some time

### ISSUE THREAD

**Issue by radokristof** [openhab/openhab-core#839]
Dear Developers!

I have a problem which reduces the reliability of my home automation system...
I have only 1 rule which uses cron triggers. However after some time (usually after a few days), the cron execution stops. Running the same rule with an “event” based trigger (like a switch) runs the rule perfectly. 
I have tried debugging the problem but I’m stuck. After enabling Debug logging for the quartz component, I have seen the logs from the scheduler, but randomly after some time this logs disappear and after that I dont have cron execution. 

I’m on 2.4 stable, but this error is not new, I have had this long time ago, but I couldnt figure it out what causes this behaviour...

**Comment by openhab-5iver** [comment]
Have you worked with people in the forum to help troubleshoot this, as it is possibly a configuration issue? It is very unlikely that you will receive any support here for a cron issue on 2.4, as much has changed since then and there were even some cron issues in 2.5M1 that are resolved in the snaphot builds.

**Comment by radokristof** [comment]
Yes I have tried that. I use a code pasted from the forum and some others report it working well and others have the same problem as me. However if something changed in the cron handling in the 2.5 release I will wait until the stable comes out and test it.
