### ISSUE TITLE
[DateTimeType] UTC string not parsed correctly

### ISSUE THREAD

**Issue by jmelhus** [openhab/openhab-core#872]
DateTimeType parse string method `2019-06-12T17:30:19Z` is parsed into `2019-06-12T17:30:19+2:00` instead of `2019-06-12T19:30:19+2:00`

how to reproduce:
-http binding: `metCache.url=https://api.met.no/weatherapi/nowcast/0.9/?lat=60.0000&lon=12.0000`
-xpath transformation, item defined as: `DateTime metPrecipitationDateTimeCreated { http="<[metCache:10000:XPATH(//weatherdata[1]/@created)]" }`
-sitemap: `Default item=metPrecipitationDateTimeCreated label="[%s]"`

string input: `2019-06-12T17:30:19Z`
string output: `2019-06-12T17:30:19+2:00`
shoult be: `2019-06-12T19:30:19+2:00`

edit: this may already be solved in the latest milestone/snapshot? I'm running 2.4 and are eagerly waiting for the milestone builds to be running again :)

**Comment by clinique** [comment]
Well, I did this unit test : 
`
    @Test
    public void testIssue872() {
        DateTimeType dt1 = new DateTimeType("2019-06-12T17:30:00Z");
        DateTimeType dt2 = new DateTimeType("2019-06-12T17:30:00+0000");
        DateTimeType dt3 = new DateTimeType("2019-06-12T19:30:00+0200");
        String dt1fs = dt1.toFullString();
        String dt3fs = dt3.toFullString();
        assertTrue(dt1.equals(dt2));
        ZonedDateTime zdt2 = dt2.getZonedDateTime();
        ZonedDateTime zdt3 = dt3.getZonedDateTime();
        zdt3 = zdt3.withZoneSameInstant(zdt2.getZone());
        assertTrue(zdt2.equals(zdt3));
    }
`
an this works fine. So I think it has been solved in between.
I think this issue can be closed.

**Comment by cweitkamp** [comment]
There have been added some enhancements for parsing and formatting precision in `DateTimeType` in #668 - which could have solved this issue. Nevertheless I added your (@clinique) unit tests in #933. Thanks for investigating.

**Comment by jmelhus** [comment]
I'm not sure this is solved. I'm running 2.5.0M2 with the same issue.

**Comment by cweitkamp** [comment]
Thanks for your feedback. I will have a look again. Which timezone do you use in your setup?

**Comment by lolodomo** [comment]
We have the unit test here:
https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core/src/test/java/org/eclipse/smarthome/core/library/types/DateTimeTypeTest.java#L195
Using "Z" as time zone in the string will lead to a ZonedDateTime built in GMT, not in local time zone.

Your problem is in fact the rendering of the date in UI and I already provided a PR to fix: PR #951 
This PR has not yet been reviewed.

**Comment by lolodomo** [comment]
Your problem is in fact the same as #832

**Comment by jmelhus** [comment]
> 
> 
> Thanks for your feedback. I will have a look again. Which timezone do you use in your setup?

In system configuration of Paper UI I have set GMT + 1 Europe/Oslo

**Comment by jmelhus** [comment]
> 
> 
> Your problem is in fact the same as #832

Yes, I believe so...

**Comment by openhab-5iver** [comment]
Since the 1.x HTTP binding is being used (no 2.x version yet), I think the issue here is that the legacy compat1x [DateTimeType](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/library/types/DateTimeType.java) does not use ZonedDateTime, so times are converted to local time. The ESH [DateTimeType](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/types/DateTimeType.java) does use ZonedDateTime and preserves timezone information.

**Comment by lolodomo** [comment]
To be tested again with snapshot 1664.

**Comment by jmelhus** [comment]
Tested snapshot 1664, sorry to say the problem did not go away...

**Comment by J-N-K** [comment]
I would agree with the analysis of @5iver. Since the compatibility layer has been removed, this issue is IMO invalid.
