### ISSUE TITLE
Add TOGGLE command to OnOffType devices

### ISSUE THREAD

**Issue by giig1967g** [openhab/openhab-core#947]
Hi,
I would like to suggest to add a new command to the Switch devices (OnOffType): TOGGLE.
This command will invert the status of the switch, ie:
if the switch in ON, the TOGGLE command will turn it OFF.

**Comment by kaikreuzer** [comment]
This was extensively discussed in https://github.com/eclipse/smarthome/pull/4638 and the conclusion was that this would be a huge breaking change that we are not willing to accept.

**Comment by splatch** [comment]
@kaikreuzer since 2.5.0 is out and 3.0 is a new horizon, does it make sense to consider `Toggle` as a first class citizen in roadmap for next release? Some automation devices already support "toggle" functionality thus adding `Toggle` command will allow having 1:1 mapping between hardware and software layer.
