### ISSUE TITLE
drop usage of personal Maven repo

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab-core#960]
The repository `https://dl.bintray.com/maggu2810/maven/` is defined in the base `pom.xml` of openHAB Core (additionally in `features/karaf/pom.xml`).

openHAB should ensure that all artifacts it consumes from this repo will be moved to the official openHAB repository (or to another Maven repository used).
It should not rely on some personal Maven repository.

I am currently running a build of openHAB Core without including this repository to check if it is necessary at all.
I will add the artifacts it needs later (if any).

**Comment by maggu2810** [comment]
The build succeeded without using that repo.
It can be removed

**Comment by kaikreuzer** [comment]
I agree that we should get rid off the usage of that repo and we can (should!) definitely remove it from our poms.

But please note that your repo is still part of the virtual repo https://openhab.jfrog.io/openhab/libs-release/ - i.e. even if the reference is removed from the poms, its artifacts are still available to the build, which is in turn still dependent on your private repo.

As we still use artifacts like [this one](https://github.com/openhab/openhab-core/blob/master/features/karaf/openhab-tp/src/main/feature/feature.xml#L246), I doubt that the build will still succeed, if I remove your repo from https://openhab.jfrog.io/openhab/libs-release/.

What do you suggest how we can get rid off your modified versions of certain bundles? I'd assume that at least a few of them could be added to https://github.com/openhab/openhab-osgiify?

**Comment by maggu2810** [comment]
We should first identify the list of bundles that are still necessary and then think about what to do.

* replace them with another OSGi version (servicemix)
* check if a newer version already support OSGi itself
* migrate it to the openHAB repo
* can be dropped already
* ...

**Comment by wborn** [comment]
The artifacts I found (based on groupId) are used by:

* [DBus Transport](https://github.com/openhab/openhab-core/blob/44b1823e9705f1af1e231079c799ee914ed66d94/bundles/org.openhab.core.io.transport.dbus/pom.xml#L17-L28)
* [Xtext feature](https://github.com/openhab/openhab-core/blob/44b1823e9705f1af1e231079c799ee914ed66d94/features/karaf/openhab-tp/src/main/feature/feature.xml#L226-L227)

---

The DBus Transport seems to be just a bundle to be able to use some libraries with OSGi.
Do you know if someone is actually still using this transport? I didn't find any usages of it.
It could also be moved to [openhab-osgiify](https://github.com/openhab/openhab-osgiify) since it is just about repackaging existing artifacts.

These libraries were build from the source code in these repos:

* https://github.com/maggu2810/dbus-java
* https://github.com/maggu2810/libmatthew-java

---

The Xtext bundles seem to be just unaltered Eclipse Orbit bundles added to a Maven repository so they can be more easily consumed.

Similary we already added the [classgraph bundle](https://github.com/openhab/openhab-core/blob/44b1823e9705f1af1e231079c799ee914ed66d94/features/karaf/openhab-tp/src/main/feature/feature.xml#L200) in #1171 to the openHAB repo.

Replacing them with other (Maven Central) artifacts doesn't seem to work well.

**Comment by kaikreuzer** [comment]
> The DBus Transport seems to be just a bundle to be able to use some libraries with OSGi.
> Do you know if someone is actually still using this transport? I didn't find any usages of it.

I honestly do not exactly remember the history here - it was once in use for the Bluetooth binding and that code was put in core as it enables general dbus communication. Afaik, it never worked very well and the Bluetooth binding uses the TinyB library for all DBUS communication, so it seems it does not require these libraries.

It will definitely not be required anymore, once https://github.com/openhab/openhab-addons/pull/7394 is merged.

If @cpmeister does not have any other info, I'd say we can happily remove this bundle from core.

**Comment by cpmeister** [comment]
I'm trying to get https://github.com/openhab/openhab-addons/pull/7394 to bring back the use of that library. I'd like to get bluetooth binding migrated away from using TinyB since it isn't maintained anymore and doesn't work with some of the newer bluez versions. TinyB use dbus under the hood so by using a dbus library we could get rid of the middleman.

I wouldn't get rid of the DBus Transport library just yet.

**Comment by kaikreuzer** [comment]
> I'm trying to bring back the use of that library

Hm, are you? Can you give some links/insights/background on that?

In https://github.com/openhab/openhab-addons/pull/7394#issuecomment-618018346, I explicitly wrote: "we could even get rid off the org.openhab.core.io.transport.dbus bundle in core." and I had the feeling that you agreed to that.

**Comment by cpmeister** [comment]
> In openhab/openhab-addons#7394 (comment), I explicitly wrote: "we could even get rid off the org.openhab.core.io.transport.dbus bundle in core." and I had the feeling that you agreed to that.

After going back and rereading that thread from the beginning I don't sense that I ever agreed to it. But it does seem to be suggested that using the https://github.com/hypfvieh/dbus-java library directly would be preferable to maintaining the DBus Transport.

If that is the case then I don't have any good reason to stop the DBus Transport library from being removed.

I withdraw my objection then. Sorry for the confusion. Carry on! 😄

**Comment by wborn** [comment]
Can you add these bundles to the openhab mvn repo on bintray @kaikreuzer?


```xml
<bundle dependency="true">mvn:de.maggu2810.p2redist/com.google.inject/3.0.0.v201312141243</bundle>
<bundle dependency="true">mvn:de.maggu2810.p2redist/org.antlr.runtime/3.2.0.v201101311130</bundle>
```

The POM and JAR can be downloaded from:

https://dl.bintray.com/maggu2810/maven/de/maggu2810/p2redist/com.google.inject/3.0.0.v201312141243/
https://dl.bintray.com/maggu2810/maven/de/maggu2810/p2redist/org.antlr.runtime/3.2.0.v201101311130/


We'd probably want to use the same groupId as we already do for the classgraph bundle:


```xml
<bundle dependency="true">mvn:org.eclipse.orbit.bundles/io.github.classgraph/4.8.35.v20190528-1517</bundle>
<bundle dependency="true">mvn:org.eclipse.orbit.bundles/com.google.inject/3.0.0.v201312141243</bundle>
<bundle dependency="true">mvn:org.eclipse.orbit.bundles/org.antlr.runtime/3.2.0.v201101311130</bundle>
```

**Comment by kaikreuzer** [comment]
Yeah, makes sense to move them to our bintray repo, indeed.
I am not completely up to date on how to upload libraries (with/without poms) to that repo and I see that @J-N-K recently added a version 2.0.0 next to the 1.0.0, so I'd first like to sync with him on how to upload additional libs.
@J-N-K What's you suggested/preferred way here?

**Comment by J-N-K** [comment]
I only added 2.0.0 because it didn't let me update 1.0.0 (releases can only be modified for one year after the initial release). I cann add them to the addons-dep package, but I'm not sure this would be the correct place. If you point meto the correct package, I can upload them and modify the POM.

**Comment by kaikreuzer** [comment]
> I only added 2.0.0 because it didn't let me update 1.0.0 (releases can only be modified for one year after the initial release)

Ah, thanks, that explains!

I think this is the place @wborn suggests, since we already have another Orbit library in there: https://bintray.com/openhab/mvn/openhab-addons-deps#files/org%2Feclipse%2Forbit%2Fbundles

**Comment by wborn** [comment]
Yes that's where it should go. Adding updated POMs is also important because some tools generate errors/warnings when they are missing or have the wrong groupId.

**Comment by J-N-K** [comment]
Done.
