### ISSUE TITLE
[rest] get request to /items/itemname does return values with the wrong encoding

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab-core#979]
A get request to the items command still doesn't return properly encoded (utf-8) strings! [Original issue](https://github.com/eclipse/smarthome/issues/4041)

To reproduce create this in an items file
```
String	TestUmlaut  "Label Umlaute: äöüß [%s]"
```

Response:
```
{
  "link": "http://localhost:8080/rest/items/TestUmlaut",
  "state": "NULL",
  "stateDescription": {
    "pattern": "%s",
    "readOnly": false,
    "options": []
  },
  "editable": false,
  "type": "String",
  "name": "TestUmlaut",
  "label": "Label Umlaute: ����",
  "tags": [],
  "groupNames": []
}
```
It seems to ascii or something else:
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 212
```

**Comment by cweitkamp** [comment]
Can you check the file encoding of your items file?

**Comment by spacemanspiff2007** [comment]
It's utf-8

**Comment by spacemanspiff2007** [comment]
If I request all items (```/rest/items```) it works properly:

```
  {
    "link": "http://localhost:8080/rest/items/TestUmlaut",
    "state": "NULL",
    "stateDescription": {
      "pattern": "%s",
      "readOnly": false,
      "options": []
    },
    "editable": false,
    "type": "String",
    "name": "TestUmlaut",
    "label": "Label Umlaute: äöüß",
    "tags": [],
    "groupNames": []
  },
```

**Comment by cweitkamp** [comment]
My findings after a quick search: The two REST endpoints indeed using different ways to create the resulting response.

https://github.com/openhab/openhab-core/blob/608507e451ca7b71171f273cfc9f3c1c7831df61/bundles/org.openhab.core.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/item/ItemResource.java#L218-L235

https://github.com/openhab/openhab-core/blob/608507e451ca7b71171f273cfc9f3c1c7831df61/bundles/org.openhab.core.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/item/ItemResource.java#L244-L265

I guess the issue is somewhere in there.

**Comment by spacemanspiff2007** [comment]
Could you restructure the code so that the mapping the same function?

**Comment by cweitkamp** [comment]
I prepared a small code update. I am not sure if it will help but it streamlines serialization of items (see https://github.com/openhab/openhab-core/pull/982).

**Comment by cweitkamp** [comment]
@spacemanspiff2007 the path is available in latest OH2 snapshot (1669). May I ask you to test again. Thanks.

**Comment by spacemanspiff2007** [comment]
I just confirmed that it works with snapshot 1706:
```
{
"link":"http://localhost:8080/rest/items/TestUmlaute",
"state":"NULL",
"editable":true,
"type":"String",
"name":"TestUmlaute",
"label":"äöß",
"tags":[],
"groupNames":[]
}
```
